### ISSUE TITLE
Appears as outdated when using gnome 3.20

### ISSUE THREAD

**Issue by tarikgraba** [negesti/gnome-shell-extensions-negesti#100]
Hi,
I'm using gnome 3.20 on Debian testing (more precisely 3.20.2-3).
When trying to update the extension from extensions.gnome.org, the extension appears as outdated.

The commit "2a430ded575e20686ba861249a7ab6033bf78936" indicates that it should work with 3.20 version.

Is there something special to do to update the extension?

T.G.

**Comment by negesti** [comment]
hi, 
the extensions.gnome.org version is not up to date. There are/were some issues that i want to fix before uploading a new version there. 
You can git clone this repository and move/link the extension file to '~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org'. "Installing" the extension just downloads a zip file and extracts it there

**Comment by tarikgraba** [comment]
Ok thx
