### ISSUE TITLE
Gap between north/south tiled windows

### ISSUE THREAD

**Issue by detly** [negesti/gnome-shell-extensions-negesti#103]
I have two displays, both 2560 px high (portrait). When I do Super+8 (to use the top half), the window height is 1240, not 1280. There is a gap of 40px to the bottom window, then the bottom window takes 1251 px. Top bar seems to be 22px.

**Comment by negesti** [comment]
Sry for this late response.. 
Some applications use really strange margins  and paddings. 

Which app causes the problem? It's really hard to debug for "all" apps

**Comment by detly** [comment]
It was Nautilus, but... strangely, it's suddenly started working. I don't know what changed, but I'll re-open this with more information if it happens again.

**Comment by detly** [comment]
Oh, I can reproduce it: two Nautilus windows on the monitor *with* the top bar. There's a gap of 26px (although my eyes aren't good enough to tell if it's really 24px).

**Comment by detly** [comment]
Gnome Terminal also has this problem, but I imagine that's because it snaps its size to a multiple of the character height? Still, it might be nice if this could be overridden.

**Comment by negesti** [comment]
yeah that would be really nice, but i have not found a way to do this. If you want turn gnome-shell into a "real" tiling wm, have a look at gTile, Shellshape and ShellTile. 
As far as I know, at least gTile overrides the gnome stylesheets and achieves a better positioning

**Comment by detly** [comment]
Alas gTile and Shellshape don't work on more than one monitor, ShellTile lacks keyboard shortcuts. Maybe soon I'll roll up my sleeves and see if these things can be combined somehow!

Thanks anyway.
