### ISSUE TITLE
always-on-top option?

### ISSUE THREAD

**Issue by OneOfOne** [negesti/gnome-shell-extensions-negesti#104]
Is there any way to add that? I'd like certain windows to start always on top

**Comment by negesti** [comment]
This should be possible. You can try it with looking glas: 

1. Focus the window you want to stay on top
1. hit Alt+F2 and type 'lg'
1. write: `global.display.focus_window.is_above()`

Is this the "always-on-top" behaviour you mean? And if so, do want to set this inside the "Applications" menu. 
Just checked the Gnome settings, is there a keyboard binding for "always-on-top"?

**Comment by negesti** [comment]
set the flag to false: 
`global.display.focus_window.unmake_above()`

**Comment by OneOfOne** [comment]
`global.display.focus_window.make_above()` is exactly what I need, and an added bonus if you can disable the border of the window too (or if you know how).

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
