### ISSUE TITLE
Feature request: disable window shadows for placed windows

### ISSUE THREAD

**Issue by detly** [negesti/gnome-shell-extensions-negesti#105]
If I place two windows above/below each other, it's usually because I want to see the contents of both at the same time. But Gnome draws a shadow around the active window, which partly obscures the contents of the adjacent window. Could the extension somehow disable this shadow for windows that are placed?

**Comment by negesti** [comment]
that sounds like a theme setting for me. I don't think that the theme can be modified from an extension sry

**Comment by detly** [comment]
Gnome itself can do it if you tile left/right (with Super+Left/Right), but I don't know if it's exposed for extensions.
