### ISSUE TITLE
Ability to match windows for movement/positioning by title string

### ISSUE THREAD

**Issue by pd5rm** [negesti/gnome-shell-extensions-negesti#108]
I'm using the 'Application size/location setting feature' panel for Thunderbird to have it moved to my second screen (e.g known bug TB https://bugzilla.mozilla.org/show_bug.cgi?id=571439).

However, the current way it works is that any dialogs (for example calendar event notifications) also get positioned in same way and grown to a very large size. I would a feature to match on windows title name (e.g .\* - Mozilla Thunderbird) and only apply the move operation then.

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
