### ISSUE TITLE
Move to workspace

### ISSUE THREAD

**Issue by sojusnik** [negesti/gnome-shell-extensions-negesti#111]
Would be nice to have an option to move an application to a certain workspace upon launch, like it's already present in [Auto Move Windows](https://extensions.gnome.org/extension/16/auto-move-windows/).

**Comment by negesti** [comment]
This is supported since #78 , but it's a feature i have never used. Not sure if it works properly with current gnome-shell version(s)

**Comment by sojusnik** [comment]
After enabling "move to workspace" it's working as expected, thanks!

But after that, the dynamic way of creating workspaces in gnome is somehow "overwritten" to a static one. That means, if I configure a program to always launch f.i. on the second workspace, and then close this program again and no other windows are present in this workspace, then it still workspace will remain. Before activating that feature, the workspace actually should have vanished. Just try it with several and you'll see what I mean.
