### ISSUE TITLE
Cleanup Readme

### ISSUE THREAD

**Issue by negesti** [negesti/gnome-shell-extensions-negesti#112]
* Move readme for older versions to wiki
* create release zip for < 3.22
* description for extensions.gnome.org

**Comment by wdoekes** [comment]
The big "**Wayland is not supported!**" almost threw me off there too. But the window moving works just fine as far as I can tell :+1:

**Comment by negesti** [comment]
Moving windows around works most of the time. The application based configuration does not work with wayland and needs a mayor re-write of the whole extension.
