### ISSUE TITLE
Proper way to save keybindings and settings

### ISSUE THREAD

**Issue by sojusnik** [negesti/gnome-shell-extensions-negesti#114]
What would be the proper way to save the settings and the keybindings of this extension, in order to restore them safely (without any version conflicts and so on) on another computer?

**Comment by negesti** [comment]
hi, 
all settings are stored in dconf under /org/gnome/shell/extensions/org-lab21-putwindow/.
you can open the settings with dconf-editor, but i don't know how do export/import a whole tree/folder of the config. 

The application based settings are stored as json in "locations" property.

**Comment by sojusnik** [comment]
Thanks, good to know!
