### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by negesti** [negesti/gnome-shell-extensions-negesti#116]
[$] gnome-shell --version
GNOME Shell 3.22.2

... on X11

No Shortcut WIN+<X> is working. When I try to assign one it just does not register the Win key.

**Comment by negesti** [comment]
that's strange, can you try to start the preferences from command line? Maybe something useful is logged: 

    gnome-shell-extension-prefs putWindow@clemens.lab21.org

**Comment by 73** [comment]
```
[$] gnome-shell-extension-prefs putWindow@clemens.lab21.org
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```
Does not log anything. Simply the Win key is not grabbed. If I try to set `WIN+E` it just takes `E`. Everything else seems to work fine.

**Comment by negesti** [comment]
as expected ...
Funny thing is i haven't changed anything  to the keyboard binding stuff inside preferences menu and I'm quite sure this worked for you before. 
* Are you able to use the win key for the build in gnome keyboard bindings?
*  Have you modified the win key using the gnome-tweak-tool or xmodmap?

**Comment by 73** [comment]
Jesus. You are right... I can not use my Win-Key any more. (I did not notice because activity is CRTL+Space here) Sry. My Bad. This ist closed...

**Comment by negesti** [comment]
in a world without walls and fences who needs windows and gates  😄
