### ISSUE TITLE
No effect from setting "Auto-Move window when created"

### ISSUE THREAD

**Issue by joelostblom** [negesti/gnome-shell-extensions-negesti#118]
First, thank you so much for making this extension! It has completely changed how I use Gnome and is one of the main reasons that I am happy with Gnome as my DE.

I have been using this addon for a few months, but just recently discovered the option to tile windows as they are created. This sounds like a great idea, but I am not able to get it to work. I have created a rule for Firefox, Gnome-Terminal, and "All". I click the save button and the rules are there next time I open the PutWindows settings, but they are not having any effects on the windows. I noticed https://github.com/negesti/gnome-shell-extensions-negesti/issues/109, but I am running on x11, so not sure that applies. And everything else I have tried with PutWindows is working fine, it is just the startup rules that are not respected.

I am running Gnome Shell 3.22.3, via Antergos (Arch) Linux. I am not sure how to see which version of PutWindows that I am using. I believed I installed it with the Gnome-extension website. The latest modification to `~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org` is Apr 16 to the medata file:

![image](https://cloud.githubusercontent.com/assets/4560057/23509671/96d2c182-ff24-11e6-8128-6700cc053dc5.png)

**Comment by negesti** [comment]
verfied this with firefox. The window is resized but the position is not updated correclty. I will check this. 
Are you able to move to the configured location using WIN + 0 ?

**Comment by joelostblom** [comment]
Yes, that works for Firefox, Gnome-Terminal, and "All".
Thanks for looking into this.

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
