### ISSUE TITLE
Windows too tall for screen when putting east/west

### ISSUE THREAD

**Issue by ahopki14** [negesti/gnome-shell-extensions-negesti#119]
Love the extension, but have a small problem when putting windows east/west.  They are a little too tall for the screen, and the bottom ~2% gets cut off.  I am running Debian 8, gnome-shell version 3.14.4.

**Comment by negesti** [comment]
That's a problem with calculating the correct padding/margin of a window and resizing it. Do you have this problem with all applications? I known for example Gnome terminal is a little bit to large but it should work for most applications
