### ISSUE TITLE
intelligenCornerSwitch variable declared multiple times in prefs.js

### ISSUE THREAD

**Issue by razvanc-r** [negesti/gnome-shell-extensions-negesti#120]
On gnome-shell 3.24 at least this is a problem as the variables should be declared only once, so settings panel can't be opened. I fixed it by removing `let` on lines 175 & 187 in `pref.js`.

Nice day!

**Comment by nergdron** [comment]
Oh, just ran into this as well on Ubu 17.04. Thanks for the fix info, would love to see it get merged in.

**Comment by razvanc-r** [comment]
I'm not gonna bother making a PR for this, kind of a hassle :P, that's why the detailed explanation

**Comment by negesti** [comment]
Thanks for the feedback!
