### ISSUE TITLE
Resizing does not work

### ISSUE THREAD

**Issue by ggirelli** [negesti/gnome-shell-extensions-negesti#121]
Hi there! I'm running Ubuntu 16.04 with GNOME Shell 3.18.5 and window resize does not appear to be working. The windows are correctly re-positioned at the corners, but no resizing takes place... maybe I have some wrong settings :( any idea what I'm doing wrong? Please let me know if you need more info! And thanks in advance! Cheers :)

**Comment by negesti** [comment]
Sound strange. Maybe you tested with an window that can not be resized?
It will take some time until i can test this with gnome 3.18..

**Comment by ggirelli** [comment]
Nope, I tested it on a normal terminal... I agree that it is weird though! If I have time I'll like into it :)

**Comment by negesti** [comment]
sry, re-reading my comment it sounds a little bit offensive. just wanted to make sure you haven't tested with one of this weird application that define a minimal size. 

As you are running gnome-shell under X11 you can try to get some debug/error messages by running the shell from the console 
```
   gnome-shell --replace &
```
Don't forget the & ;) The actual resize is called in extension.js around line 770. You can try this in looking glas too: 
```
  global.display.focus_window.move_resize_frame(false, 10, 10, 400, 400);
```
Note: This call will not work if it is maximized vertical or horizontally

**Comment by ggirelli** [comment]
@negesti no worries, no worries! Thanks for the suggestion, I'll check that in the we.

**Comment by domdomegg** [comment]
This may be a really stupid answer but might just work as I have found out. GNOME has some built in ones that also move it but don't resize. To remove the defaults open up `org.gnome.desktop.wm.keybindings` in dconf editor, and set all the `move-to-corner-<dir>` to blank (`[]`). They try setting your desired keyboard shortcuts in `Gnome tweak tool > Extensions > Put windows settings > Keyboard Shortcuts`.

**Comment by negesti** [comment]
No Response, closinf
