### ISSUE TITLE
Missing support for wayland

### ISSUE THREAD

**Issue by negesti** [negesti/gnome-shell-extensions-negesti#123]
At the moment wayland is not fully supported. Moving windows around should work in most cases. 

Known issues: 
**Keyboard binding**
Bindings used by gnome-shell are not forwarded to the extension. Adjust the binding and restart gnome-shell. Removing them from the gnome config is not enough.

**Preferences**
The prefs window crashes with a segfault of libwnck. Until there is a proper way to get the name of all windows in wayland this is a blocker.

**Comment by negesti** [comment]
Check #104, #108 and #134 when starting the work on this one

**Comment by dutgcom** [comment]
There is an alternative extension that does most of the things that put windows does but also works under wayland - https://github.com/velitasali/gnome-shell-extension-awesome-tiles

**Comment by negesti** [comment]
@dutgcom thanks for the hint. look like bindings are working with Main.wm... but the application based config relies on wnck and is not supported by awesome-tiles as far as I can tell

**Comment by lostping** [comment]
There is another extension that saves and restores window positions and moves windows to other monitors as well AND this also works with wayland.

[https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager)

They don't seem to use wnck.

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
