### ISSUE TITLE
There was an error loading the preferences dialogue for Put Window:

### ISSUE THREAD

**Issue by maxcr** [negesti/gnome-shell-extensions-negesti#124]
```
TypeError: redeclaration of let intelligenCornerSwitch

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
  ```

**Comment by negesti** [comment]
this should be fixed in the current github version

**Comment by maxcr** [comment]
If I use github version my whole shell crashes, and kills all running progs.

**Comment by negesti** [comment]
That sounds really strange. I'm using the current version without problems.
What's your gnome she'll version? The redeclaration is normally just a warning.

**Comment by agreco** [comment]
How do I install this plugin via cloning this repo?

**Comment by negesti** [comment]
Have a look at the [wiki](https://github.com/negesti/gnome-shell-extensions-negesti/wiki#manual)

Basically you need a folder called "putWindow@clemens.lab21.org" inside ~/.local/share/gnome-shell/extensions/

**Comment by negesti** [comment]
@maxcr can i close this issue?

**Comment by agreco** [comment]
I followed your steps and putWindow does install, but the script error still occurs when accessing the configuration from Tweak.

**Comment by negesti** [comment]
I guess you are on the master branch. should work now after git pull or checkout develop

**Comment by agreco** [comment]
I'm on develop, for sure

**Comment by negesti** [comment]
the redeclaration was fixed in #120 nearly two months ago. Maybe something else kills the preferences for you? can you run it from console and check the log?

     gnome-shell-extension-prefs  putWindow@clemens.lab21.org

**Comment by agreco** [comment]
As per the instructions on the wiki, this `putWindow@clemens.lab21.org` doesn't exist within the repo.

**Comment by agreco** [comment]
I

**Comment by negesti** [comment]
Just create the folder and move/link the files. I will update the wiki. I removed the subfolder ages ago and cloned the repo into a folder with the correct name.

Gnome shell only recognizes the extension if the folder name matches the name defined in metadata.json...

**Comment by negesti** [comment]
I've added installation instructions to the readme and uploaded a release zip that can be installed using gnome-tweak-tool

**Comment by AKoetsier** [comment]
Had the same problem. After manually installing the latest zip (v20.1.0) I can open the preferences again.

**Comment by agreco** [comment]
I can confirm that the lastest release zip, does allow preferences to be accessed.
