### ISSUE TITLE
Moving from corner to edge doesn't size properly

### ISSUE THREAD

**Issue by akoyich** [negesti/gnome-shell-extensions-negesti#128]
If I use the shortcut to move a window to the top left corner ("Move to top left corner"):

![put-window_01](https://user-images.githubusercontent.com/782450/28285661-d3666650-6af2-11e7-87e5-f22ed837da0b.jpg)

And then I use the keyboard shortcut to move that window to fill that same side ("Move to left"), the window's width is set to the "West width - Second" width.

![put-window_02](https://user-images.githubusercontent.com/782450/28285685-e256d460-6af2-11e7-8627-188c35557cd0.jpg)

![put-window_03](https://user-images.githubusercontent.com/782450/28285747-12524262-6af3-11e7-99a3-03ae2f888446.jpg)

Is there a setting that I'm missing so that when I move a window from the corner to the side, the window will have the "West width - First" width?

**Comment by negesti** [comment]
There is no such option. Before moving a window the extension calculates the current width/height and checks which configuration is the "nearest" and resizes it to the next configured size.
