### ISSUE TITLE
Application based size and position applies to child windows

### ISSUE THREAD

**Issue by cytech** [negesti/gnome-shell-extensions-negesti#132]
## Expected Behavior

place window by application (Thunderbird) places fine
but when opening  child (write new email) placement applies to the new child window

Child window should ignore main window placement settings

## Possible Solution

Is there a workaround to set just the placement of the initial main window?
Or am I doing something wrong.....

## Steps to Reproduce (for bugs)

1. applications - add application - Thunderbird
2.width 95
3.height 100
4.x position =5   y position =0

## Your Environment

* gnome-shell version: 3.26
* affected application(s) (e.g. chrome, nautilus, all, ...) all
* distribution ubuntu 17.10 under xorg

**Comment by negesti** [comment]
Unfortunately I can not really fix this. put windows uses the "wm class" name of the application to recognize the application and which configuration should be used. child windows always have the same wm class

**Comment by cytech** [comment]
understood, thank you
i was looking at the code and when I get a chance was going to try and
add:  if the class is already opened, then ignore additional put operations on that class.
thanx

**Comment by negesti** [comment]
Is relativ to #108
