### ISSUE TITLE
"Put Windows" shell extension might "steal" keystrokes, before it reaches other applications

### ISSUE THREAD

**Issue by LeadManPL** [negesti/gnome-shell-extensions-negesti#133]
"Put Windows" shell extension might "steal" keystrokes, before it reaches other applications
This bug report should be considered together with report:
https://github.com/symless/synergy-core/issues/6195

## Expected Behavior
I expect shortcuts used by "Put Windows" to be usable by other software also. I know this sound unnatural at first sight, but first please look at the bug reported in Synergy project, and you will understand me.

## Current Behavior
I suspect, that "Put Windows" shell extension "steals" keystrokes, before it reaches other applications

## Steps to Reproduce (for bugs)
Reproducible: almost always.
0. Get Server with Ubuntu 17.10
1. Install Gnome extension https://extensions.gnome.org/extension/39/put-windows/
2. Configure it's shortcuts to use Ctrl+Alt+NumPad to place windows in screen position
3. Install and Start Synergy
4. press i.e. Ctrl+Alt+NumPad_7 to place some window in Upper Left part of the screen. Works OK - window is moved on the server.
5. move cursor to client
6. press i.e. Ctrl+Alt+NumPad_7 to place some window in Upper Left part of the screen. Here is failure. instead of moving window on the client, again window on the server is moved.

## Your Environment
* gnome-shell version: 
  Server: Ubuntu 17.10 (GNOME 3.26)
  Client: Windows 7
* affected application(s) (e.g. chrome, nautilus, all, ...)  1.8.8-stable-25a8cb2

**Comment by negesti** [comment]
which application gets the key stroke is handled by the window manager. i assume you are using wayland? With X11 this works as expected (at least with my virtual machine using kvm )

**Comment by LeadManPL** [comment]
I assume yes, as I can see some Xwayland processes (see below). Do you think I should report this bug to Wayland developers?

patben@patben-amd:~$ ps ax | grep wayland
  999 tty1     Ssl+   0:00 /usr/lib/gdm3/gdm-wayland-session gnome-session --autostart /usr/share/gdm/greeter/autostart
 1079 tty1     Sl+    0:00 /usr/bin/Xwayland :1024 -rootless -noreset -listen 4 -listen 5 -displayfd 6
 1521 tty2     Ssl+   0:00 /usr/lib/gdm3/gdm-wayland-session env GNOME_SHELL_SESSION_MODE=ubuntu gnome-session --session=ubuntu
 1603 tty2     Sl+   13:21 /usr/bin/Xwayland :0 -rootless -noreset -listen 4 -listen 5 -displayfd 6

**Comment by negesti** [comment]
Afaik this is a known problem in wayland.
Last time I tried wayland this was the biggest issue for me. Wayland was completly unusable with rdp, vnc,  virt*..
