### ISSUE TITLE
Add support for sticky/pinned option in Applications

### ISSUE THREAD

**Issue by guyou** [negesti/gnome-shell-extensions-negesti#134]
## Expected Behavior

I'm using multiple workspaces on multiple screens. I like to have a some application (Thunderbird for example) visible on every workspace.
I would appreciate to indicate in preferences that such application should have the pinned/sticky option activated in order avoid doing this stuff each time I started my desktop.

## Current Behavior

Currently, I do it myself when desktop is started: once applications appears, I right click on title bar and select option "Always on visible workspace".
I think this is related to https://developer.gnome.org/libwnck/stable/WnckWindow.html#wnck-window-is-pinned or https://developer.gnome.org/libwnck/stable/WnckWindow.html#wnck-window-is-sticky

## Your Environment

* gnome-shell version: 3.18.5
* distribution: Ubuntu

**Comment by negesti** [comment]
This is kind of related to #104. aka yet another step away from supporting wayland :(

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
