### ISSUE TITLE
Enhhancement to retain window size on Application-based Auto-move when created

### ISSUE THREAD

**Issue by ahhsia** [negesti/gnome-shell-extensions-negesti#135]
## Expected Behavior
Instead of forcing the window to have the specified height, width, and x,y position, allow for an option to just Auto-move it to the specified screen while retaining its native size and placement, but now on a different screen.

## Current Behavior
All the windows including dialog boxes are force resized and positioned to the settings. This makes many of them require a resize in order to be useable. 

## Context

This is for a multimonitor setup. I have a few apps that don't remember their last position and always pop-up on my secondary screen in the lower left (0,0) corner. I use Put Windows to auto-move them to the primary screen (Screen 2 in my case) Auto-moving them to Screen 2 while retaining their size would be most useful. 

## Your Environment

* gnome-shell version: 3.22
* affected application(s) all
* distribution : RHEL7

**Comment by negesti** [comment]
quick fix for this: just set width and height to zero

**Comment by negesti** [comment]
should work now. Would be nice if somebody can test this ;)

**Comment by negesti** [comment]
Works for me. Closing this
