### ISSUE TITLE
'Moving to left/right' moves the window across screen

### ISSUE THREAD

**Issue by Valeesi** [negesti/gnome-shell-extensions-negesti#140]
Steps to Reproduce:
Dual-display setup. Focus and maximize a window in the right screen. 'Moving to left'. 

Expected Behavior:
It should move to the left side on the right screen. 

Current Behavior
It actually jumps to the right side of the left screen. After 3 x 'Moving to right', it jumps across to the left side of the the right screen. 

Context
I expect 'Moving to right/left' never to move windows across screens as there are already shortcuts such as 'Moving to the right/left screen' existing. I failed to find a setting that could disable this feature.

Environment:
Ubuntu 18.04 LTS

**Comment by negesti** [comment]
Not in front of my notebook but i think you are looking for "always use
multiple width"

Allan Wang <notifications@github.com> schrieb am Mi., 2. Mai 2018, 09:23:

**Comment by Valeesi** [comment]
Thank you. Now it works! Any particular reason this "across screen" feature is bundled with "multiple width/height"?

**Comment by negesti** [comment]
move to screen was added later. earlier it was just possible to move the window to left/right and the option was added to use "split mode" on both screens
