### ISSUE TITLE
Does not remove empty workspaces

### ISSUE THREAD

**Issue by lonix1** [negesti/gnome-shell-extensions-negesti#141]
If there are no more windows on workspace 1, then it remains empty. It should be removed, and all workspaces shifted up.

In gnome tweak tool -> workspaces -> dynamic workspaces option, that would be the expected behavior, but this extension seems to change that.

So the empty workspace remains at the top (or middle) of the list, and I need to manually shift all windows up one by one.

**Comment by negesti** [comment]
The workspace is only removed if you open the "gnome manu" e.g. press super. 

If "move to workspace" is not enabled, the extension doesn't mess around with the workspaces (see #111)

**Comment by negesti** [comment]
See #142 142
