### ISSUE TITLE
Will break with gnome-shell 3.30

### ISSUE THREAD

**Issue by eddy-geek** [negesti/gnome-shell-extensions-negesti#143]
Extension does not start on Fedora 29 Beta, gnome-shell 3.30 RC (3.29.91-1)

## Current Behavior
Following error is printed:

    TypeError: global.screen is undefined

## Possible Solution
See https://github.com/home-sweet-gnome/dash-to-panel/issues/434 and fix https://github.com/micheleg/dash-to-dock/pull/770

> Basically global.screen moved to global.display, while all the workspace related features have been moved to the WorkspaceManager and displays are managed by DisplayManager.

Also the built-in extensions update [commit](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/6583eae6225039b6b711918eff3a7cd0d03a42ca).

## Your Environment
* gnome-shell version: 3.29.91-1
* distribution : Fedora 29 Beta

**Comment by negesti** [comment]
Thank's for the the info and the solution hint!
I'm not sure if i will have enough time to setup a fedora 29 vm and test this with gnome-shell 3.29. Maybe this will not be fixed before I upgrade my fedora notebook to 29 :(
