### ISSUE TITLE
for newest gnome package in archlinux, the plugin cannot start

### ISSUE THREAD

**Issue by terryding77** [negesti/gnome-shell-extensions-negesti#145]
for newest gnome package in archlinux, the plugin cannot start

## Expected Behavior

can normally start after boot.
## Current Behavior

![image](https://user-images.githubusercontent.com/11759109/45728634-57dbad00-bbfb-11e8-8c9c-c0ee595234aa.png)

## Steps to Reproduce (for bugs)

1.update system `sudo pacman -Syu` in archlinux and reboot

## Your Environment

* gnome-shell version: 
![image](https://user-images.githubusercontent.com/11759109/45728717-d89aa900-bbfb-11e8-952f-8e38323b384b.png)

* archlinux

**Comment by negesti** [comment]
The aur package is already referencing commit 787100c this should be fine. 
Can you restart the shell from console and check if there are any relevant log messages?

`` gnoms-shell --replace &``
Don't forget the & :)

**Comment by terryding77** [comment]
it cannot start with the version in https://extensions.gnome.org/ 
but as @mrmstn  says, I try to use `yaourt -S  gnome-shell-extension-put-window-git ` and restart gnome, it works! thanks a lot.

**Comment by terryding77** [comment]
with command `gnome-shell --replace &` 
I only see those message in terminal
and I don't make sure whether it relevant or not. @negesti 
>  (gnome-shell:26608): GLib-GObject-WARNING **: 12:28:46.302: invalid (NULL) pointer instance
> 
> (gnome-shell:26608): GLib-GObject-CRITICAL **: 12:28:46.302: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> (gnome-shell:26608): GLib-GIO-CRITICAL **: 12:28:46.394: Error while sending AddMatch() message: The connection is closed
> 
> (gnome-shell:26608): GLib-GIO-CRITICAL **: 12:28:46.394: Error while sending AddMatch() message: The connection is closed
> 
> (gnome-shell:26608): GLib-GIO-CRITICAL **: 12:28:46.394: Error while sending AddMatch() message: The connection is closed
> Gdk-Message: 12:28:46.405: gnome-shell: Fatal IO error 0 (Success) on X server :1.
>

**Comment by negesti** [comment]
ok reading your first post again I see the problem you have installed the new gnome-shell package (3.30) using pacman and extension from extensions.gnome.org

This version doesn't contain the fix for #143 #144 . I thought you installed the new extension package from aur.

**Comment by negesti** [comment]
New version (v23.0) will be available at extensions.gnome.org after review
