### ISSUE TITLE
new version stopped working with 3.22.2 (Debian Stable)

### ISSUE THREAD

**Issue by jmtd** [negesti/gnome-shell-extensions-negesti#146]
I've been a happy user for a long time. Yesterday I was prompted by Shell that an update was available, so I attempted to install it. The result was the plugin not installed.

## Expected Behavior

I expected the plugin to be installed and enabled.

## Current Behavior

Presently it's not enabled and I am unable to find a version (via the drop-downs on extensions.gnome.org) that will install for my GNOME version (Debian Stable's, 3.22.2).

## Possible Solution

I'm hoping that some metadata can be frobbed somewhere to fix this.

**Comment by jmtd** [comment]
possibly jumped the gun a little; extension version 21 works; versions 22 & 23 are offered but do not work (simply do not enable once installed)

**Comment by negesti** [comment]
Thanks for reporting this. As the are no major changes since v21 expect i removed 3.22 from the supported version and disabled v22 and v23

**Comment by negesti** [comment]
Following changes are missing in v21
#126 - Slovak translation
#136 - multiple "center" positions
#137 - moveFocus fix
