### ISSUE TITLE
Option to not move windows to other screens

### ISSUE THREAD

**Issue by DrRob** [negesti/gnome-shell-extensions-negesti#148]
## Requested Behaviour
An option in the settings to allow users to state a preference for NOT moving windows to other screens when cycling through "Move to left/right" sizes.

## Current Behaviour
On the fourth press, the window jumps to the next screen along instead of cycling back around to the first size.

## Steps to Reproduce
1. Test on a PC with two screens arranged horizontally
2. Have "Move to left" enabled in Keyboard Shortcuts in the Put Windows settings
3. Put a window on the right-hand screen
4. Press the "Move to left" shortcut three times - the window jumps to the left edge and cycles through
three sizes
5. Press the "Move to left" shortcut one more time - the windows jumps to the screen to the left - I don't want it to do that.  It takes three shortcut presses in the opposite direction to move it back again, which is tedious.

## Context
I don't want the window to jump to another screen in this situation - there is another shortcut for doing that.  I just want it to cycle through the available sizes.

## Your Environment
* gnome-shell version: gnome-shell --version = GNOME Shell 3.28.3
* affected application(s): all
* distribution: Ubuntu 18.04.1 LTS

Thanks.

**Comment by negesti** [comment]
It's the first option under common settings: "Always use multiple widhts/heights"

**Comment by negesti** [comment]
@DrRob  Can I close this issue?

**Comment by DrRob** [comment]
Oh!  That's it!  Sorry, it did not occur to me from that wording that this option would do would do what I want.  I thought that turning this off would mean, "Don't use multiple widths/heights".  How about, "Include move to screen when cycling width/heights"?

Closing, thanks.

**Comment by negesti** [comment]
That's true ..
How about "Keep window on current screen" ? "Include move to screen" negates the question/option.
There are tooltips for most of the options. Including the "easter egg" at 'Intelligent corner movement' ;)

**Comment by DrRob** [comment]
Yes, "Keep window on current screen" is better, thanks.
