### ISSUE TITLE
Application settings are overwritten

### ISSUE THREAD

**Issue by toupeira** [negesti/gnome-shell-extensions-negesti#150]
## Expected Behavior

Settings are stored per application.

## Current Behavior

Saving the application settings overwrites the settings of all the defined apps with the currently selected app's settings. I looked at the `locations` key in dconf to verify it's changed there as well, and if I fix the values there manually the behaviour is correct, so this looks like a bug in the prefs dialog.

## Steps to Reproduce (for bugs)

1. Add application with some settings
2. Add a second application with different settings
3. Save the settings
4. Select the first application, which now also shows the second application's settings

## Context

I'd like to have some apps split to the left, and some to the right.

## Your Environment

* gnome-shell version: 3.30
* extension version: 24
* distribution: Debian sid

**Comment by negesti** [comment]
That's kind of an known issue. The save button only saves the current configuration. I have never tried to add multiple apps and save once. 
It should work as expected if you save the settings before adding a second application

**Comment by toupeira** [comment]
Yeah, I noticed once I had my initial setup I could add more applications one at a time without problems.

**Comment by Lewis65** [comment]
> That's kind of an known issue. The save button only saves the current configuration. I have never tried to add multiple apps and save once.
> It should work as expected if you save the settings before adding a second application

I am saving between apps and the settings still look to be copied to previous apps. Pretty sure it is a bug, not a UI issue, because closing and reopening the settings resulted in it working as expected.

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
