### ISSUE TITLE
Corner placement does not correctly size windows

### ISSUE THREAD

**Issue by skjoedt** [negesti/gnome-shell-extensions-negesti#151]
## Expected Behavior
Corner placement should be in exact sizes of the 4-grid window placement, not based on previous window size.

## Current Behavior
Corner placement scales the window seemingly randomly.
Side-by-side placement work, e.g. top/bottom or left/right. The bug is only for corner placement. 
![peek 2018-11-13 13-05](https://user-images.githubusercontent.com/5172915/48412581-6222af00-e745-11e8-8d8d-9ec61e359577.gif)

## Steps to Reproduce (for bugs)
I have bound the corner "move to X corner" to various SHIFT+SUPER+{Q,E,C,Z} hotkeys and try to use these to put windows in the 4 grid corners. Similarly I have bound "Move to top/left/bottom/right" to SHIFT+SUPER+{W,A,X,D} and "Move to Center" to SHIFT+SUPER+S

## Your Environment
Ubuntu 18.04 (hours old install) with previously installed (but disabled) gnome extension called "global application menu", otherwise vanilla Ubuntu 18.04.

**Comment by negesti** [comment]
that looks like the gnome-terminal? That's one of ~ 5 apps i know that do not report the correct size and are not resizing properly. 
If I remember correctly gnome-terminal is rounding the provide pixel height to "number of lines" 

Maybe you should try something like  [Terminator](https://gnometerminator.blogspot.com/) ?

**Comment by negesti** [comment]
@skjoedt Are you experiencing the problem with any other application or only with the gnome-terminal? Just tried again, you can not resize the terminal to "fit the corner". This would require a logic that 
1. resize the window
1. check actual window widht/height after resize
1. re-calculate x and y if widh/height don't match the requestest values

**Comment by Socob** [comment]
@negesti I’m on Ubuntu 18.10 here, and for what it’s worth, for me the corner sizing also currently does not work for any application (not just gnome-terminal). I tried it with gedit and nautilus. For applications like these, which remember the size of the last opened window, it seems when I place a window into a corner once, windows opened after that are opened with the correct size for corner placement for some reason. However, if any of the new windows are resized, everything after that is completely messed up again.

So I don’t think it’s an application-specific issue. Do you want me to try any particular application?

![screenshot](https://user-images.githubusercontent.com/1915511/53302655-f205e800-3860-11e9-933f-ded65c9a6c92.gif)

**Comment by jhakonen** [comment]
I'm seeing the same thing on Ubuntu 19.04 as Socob in the above comment. Happens with any applications, not just the the terminal.
