### ISSUE TITLE
Extension stops working in Ubuntu 18.10 as soon as I lock and unlock the GNOME session

### ISSUE THREAD

**Issue by freeseek** [negesti/gnome-shell-extensions-negesti#152]
I am no expert with GNOME 3.30.1 so I am not sure whether this is an issue with the extension or with GNOME 3.30.1. However, since the issue is perfectly reproducible, I will share my experience.

Since I have updated to Ubuntu 18.10, when I start the computer the extension works fine. Super+7, Super+9, Super+1, Super+3 all work as expected by snapping windows to the corners. However, if I lock the GNOME session (with Super+L) and then attempt to snap the windows to the corners after I unlock the session, it feels as if the Super button is not doing anything: instead of snapping windows I end up typing characters 7, 9, 1, 3, etc.

I thought this is most likely a GNOME issue. However, if I uninstall the extension from the installed extensions page: https://extensions.gnome.org/local/
And the re-install the extension: https://extensions.gnome.org/extension/39/put-windows/
It immediately works again without requiring me to restart the GNOME session.

I am no expert but I would be happy to debug the issue if I am given proper directions.

**Comment by negesti** [comment]
I'm not sure what exactly happens on screen lock/unlock. But I guess, the _init and destroy method inside extension.js are called and all listeners are added/removed. As you are using ubuntu i guess the guys from canonical have added some fancy untested stuff to lightdm....

Do you find any extension and/or keybinding related logs in journalctrl or /var/log?

**Comment by freeseek** [comment]
I actually believe that since Ubuntu 18.04 the lightdm login manager has been dropped in favor of gdm3. What exactly do you want me to look for in /var/log? Also, just to make sure, locking the screen is not the same as logging out of a session and the problem arises when locking the screen.

**Comment by negesti** [comment]
Just tried, you can restart the gnome-shell from terminal, lock the screen and the shell is not restarted. 
Please open a terminal and run `gnome-shell --replace &`. All gnome logs should now be visible in this terminal. 

Dont forget the & at the end. This can get really funny once you hit ctrl + c :)

**Comment by 73** [comment]
This is not reproduceable for me using 18.10 and the development branch on
a daily basis.

**Comment by freeseek** [comment]
This is weird. When I first run `gnome-shell --replace &` the session became unresponsive. Applications would not respond to the mouse and the pressing keys on the keyboard would not do anything. There were a lot of errors being displayed on the terminal. I rebooted and tried again, this time redirecting the output to files. But the weirdest thing is that now I cannot reproduce the previous behaviour anymore. Now if I lock the session and then I unlock the session, Put Windows is still working. I am baffled. I cannot reproduce the bug anymore.

**Comment by negesti** [comment]
Sounds like a "fix" to me?

**Comment by freeseek** [comment]
I am thinking more and more that this is some sort of GNOME issue. Right now I don't have the issue anymore. But I also don't have the GNOME issue of having to locked the session twice with Super+L (pressing the combination once used to bring to an almost unresponsive GNOME state). The two issues seemed to go together. If nobody else is complaining, do please feel free to close this issue.
