### ISSUE TITLE
Gap when moving window to bottom

### ISSUE THREAD

**Issue by rezan** [negesti/gnome-shell-extensions-negesti#155]
When I move a window to the bottom using a shortcut, there is a gap between the window and the actual bottom.

## Current Behavior
![screenshot from 2018-12-28 13-28-27](https://user-images.githubusercontent.com/1030507/50527169-9b746b80-0ab4-11e9-8c0d-0e851710975b.png)

## Steps to Reproduce (for bugs)

1. Move to bottom left/right shortcut

## Your Environment

* Gnome 3.28.2
* Ubuntu 18.04.1

**Comment by rezan** [comment]
Its all windows. Maybe its related to the top bar? The gap on the bottom is around 35px, which is about the height of the top bar.

![screenshot from 2018-12-30 11-06-04](https://user-images.githubusercontent.com/1030507/50548959-21162980-0c23-11e9-9a84-ca2f416ed7b8.png)

**Comment by negesti** [comment]
strange, have you tried to enable "always ignore top panel"

**Comment by rezan** [comment]
Ya, didn't change the behavior, still a gap.

**Comment by negesti** [comment]
Just installed ubuntu 18.04 in boxes and can reproduce the problem now. In my case, the gap only exists on the first move to the bottom of the screen (south). e.g. must be a problem with the initial "calculation" of the y position and height of the window...

Never had that behaviour with my fedora workstation. Just change distro? ;)

**Comment by negesti** [comment]
Just installed ubuntu 18.04 in boxes and can reproduce the problem now. In my case, the gap only exists on the first move to the bottom of the screen (south). e.g. must be a problem with the initial "calculation" of the y position and height of the window...

Never had that behaviour with my fedora workstation. Just change distro? ;)

**Comment by rezan** [comment]
> Just change distro?

Lol

Is there a workaround to get it to recalculate better? Anyway, this isnt a big deal, im ok with the small gap. I figured I would ask. Thanks for taking the time to debug this!

**Comment by negesti** [comment]
Basically there is one method that moves the window around, could  be an easy fix. I will check this tomorrow. Today i just setup a vm during a skype call at work  ;)

**Comment by Bu3a3a** [comment]
I've got the same problem but for me it happens only with a terminal window. All other system or application windows work just fine.  
Note that there is a small gap on the right side too. 

Gnome 3.28.2
Ubuntu 18.04.1
Also I use the GNOME Tweaks extension to hide the top bar ("always ignore top panel" is great and worked just fine). 

![image](https://user-images.githubusercontent.com/8478209/50991233-41988a80-1525-11e9-850e-bb8b485276c2.png)

**Comment by Socob** [comment]
@negesti Did you find anything? I’m still seeing this (for all windows, not just terminals).

**Comment by negesti** [comment]
I checked the calculation but can not find an real bug. I have changed/improved/re-implemented the whole thing around 20 times in the last 4 years and never got a perfect solution for all distros and applications. 
If you willing to fix this on ubuntu that would be great. I will not have the time for that in the near future

The final calculation for the positionand size are perfomed in extension..js#807. With some global.log messages is quite easy to get the real values when moving windows around (there is no debug mode). 

Either it's a problem with the theme/application or it's because i have forgotten to include the topPanelHeight somewhere.

**Comment by rezan** [comment]
This commit fixed it for me: https://github.com/negesti/gnome-shell-extensions-negesti/commit/d44a59925ddc7d0549391373eb866419e904b07c

However, I had to manually patch that in as my local install didn't contain the commit. I seem to be 1 release back or something.

**Comment by rezan** [comment]
Feel free to close this issue...

**Comment by negesti** [comment]
Thanks for looking into this! 
The fix from #149 is part of the current develop branch and included in v24.1 under releases. Maybe you should update your local version with git (or install the release zip)?

**Comment by Socob** [comment]
I can try that. I got the extension from https://extensions.gnome.org, which only seems to have v24 (not v24.1).

**Comment by chui2ch** [comment]
I just installed the git version on Ubuntu 18.04.2 and now I can move windows all the way to the bottom of my primary screen. It seems there is still an issue with moving windows all the way to the top. This is only an issue on the monitor with the top bar. My secondary monitor works just fine.

![image](https://user-images.githubusercontent.com/40251476/54481838-f42be880-4807-11e9-9287-db99c18589b1.png)

**Comment by negesti** [comment]
Have you tried "Always ignore top panel" ?

**Comment by chui2ch** [comment]
> Have you tried "Always ignore top panel" ?

That worked, Thanks! I would have never thought about selecting it since it worked up until this last week. Thanks so much for the suggestion!
