### ISSUE TITLE
Just upgraded Fedora 28 to Fedora 29 and the plugin stopped working

### ISSUE THREAD

**Issue by dmitry-saritasa** [negesti/gnome-shell-extensions-negesti#156]
Hello,

Tried to uninstall and install the plugin through browser extension manager - didn't help, the plugin doesn't work

![image](https://user-images.githubusercontent.com/1747653/51780988-39655100-20c8-11e9-8ca7-4eb54ef198c3.png)

**Comment by negesti** [comment]
Strange, running fedora 29 since it was released.
Have you tried using x instead of wayland?

**Comment by dmitry-saritasa** [comment]
Weird after PC restart it worked. Ok close it.
