### ISSUE TITLE
“Intelligent corner movement”: description is unclear/confusing

### ISSUE THREAD

**Issue by Socob** [negesti/gnome-shell-extensions-negesti#157]
## Expected Behavior
The description/tooltip for the “intelligent corner movement” option should clearly describe what it does.

## Current Behavior
The tooltip currently says

> Quite difficult to describe. Enable it and move a window from S to E, 

which not only doesn’t describe the functionality, but also looks like an incomplete sentence due to the trailing comma (and space).

## Possible Solution
I found the following lines:
https://github.com/negesti/gnome-shell-extensions-negesti/blob/1d7f7d470f35c05392ef05b8fdde5fcad295e7e3/schemas/org.gnome.shell.extensions.org-lab21-putwindow.gschema.xml#L28-L30
That summary seems to describe the functionality much better.

**Comment by negesti** [comment]
Thanks for looking into this
