### ISSUE TITLE
Duplicate default keyboard shortcuts

### ISSUE THREAD

**Issue by Socob** [negesti/gnome-shell-extensions-negesti#158]
## Expected Behavior
The default keyboard shortcuts in the extension should not have any conflicts, i. e. they should not define the same shortcut for multiple actions.

## Current Behavior
The keyboard shortcuts `<Super><Shift>Left` and `<Super><Shift>Right` are defined for two different actions at the same time (“Move to the screen on the left/right side” and “Move the focus to the left/right screen”). Although the order of `<Super>` and `<Shift>` is reversed in the source file, this is still problematic because both are essentially the same shortcut.

https://github.com/negesti/gnome-shell-extensions-negesti/blob/cad5879df0e8b4c5eeb0a028b7674d0f4b123f43/schemas/org.gnome.shell.extensions.org-lab21-putwindow.gschema.xml#L164-L171

https://github.com/negesti/gnome-shell-extensions-negesti/blob/cad5879df0e8b4c5eeb0a028b7674d0f4b123f43/schemas/org.gnome.shell.extensions.org-lab21-putwindow.gschema.xml#L251-L258

## Possible Solution
Another default shortcut should be used for one of the two actions in both cases.

**Comment by negesti** [comment]
Absolutely agree. I can remember that I have changed default bindings for move focus N/O/S/W to use the vim bindings around 2 years ago. Just checked in was in August 2015 (#82). 
Seems like i missed them back then. As i never used the move focus part I never realized that

@73 Ok for you if we use the vim style for move focus to other screen too? (Super + Shift + J and L )

**Comment by negesti** [comment]
I changed move focus left/right to "U" and "O".
