### ISSUE TITLE
Possibility to move instantly from vertical half to horizontal half

### ISSUE THREAD

**Issue by VariabileAleatoria** [negesti/gnome-shell-extensions-negesti#159]
When the window is in a vertical half of the screen, and you want to move it to an horizontal half (e.g. from right side to top side) you have to first move to the corner (top right) by moving in the desired direction (top). Why does it work like that? I mean, if I wanted to move to the corner I would have used the key-binding for moving to the corner.
Why doesn't the top bot left right work as an alias for top bot left right halves of screen?
I'm thinking to something like Unity, where numpad represented the screen (so the corner number are obviously screen corners, 5 is center/maximize, and the others are for screen halves).
Is it possible to make it work?

**Comment by negesti** [comment]
Have a look at "intelligent corner movement" in the setting. That should do the trick

**Comment by VariabileAleatoria** [comment]
Thanks, removing that option worked perfectly!
do you have any idea on why the center/maximize is not working properly, but on the second click, instead of maximizing, it moves to bottom corner?

**Comment by negesti** [comment]
Not sure, but i think i have implemented a "restore position" option some time ago, maybe that helps
