### ISSUE TITLE
"Moving to corner" configured as "Both" is not honored

### ISSUE THREAD

**Issue by paolo-losi** [negesti/gnome-shell-extensions-negesti#161]
## Expected Behavior

When "Moving to corner" is configured as "Both" I expect that when a move the
window to a new corner position the window is resize both horizontally and vertically.

## Current Behavior

The window is first moved without resizing only at the second attempt is resized

## Your Environment

* distribution stock Ubuntu 18.10
* gnome-shell version: 3.30.2

**Comment by negesti** [comment]
@paolo-losi can you please test the newest git version?

**Comment by paolo-losi** [comment]
@negesti tested the master branch. It works! Thanks

**Comment by negesti** [comment]
Thanks, I will check the upload a new version to extensions.gnome.org
