### ISSUE TITLE
Resizing works with everything except terminal

### ISSUE THREAD

**Issue by trogdor-dev** [negesti/gnome-shell-extensions-negesti#165]
## Expected Behavior

Expect window tiling to work for every application, including terminal windows.

## Current Behavior

The window tiling seems to work perfectly for every application except for terminal windows. They never snap exactly to the same dimensions that other windows snap to. For example, if I push a browser to the upper left corner, it fills exactly 1/4 of the available screen. But if I push a terminal window to the upper left corner, there is a slight gap on the right and bottom. It does this in every corner and side. I have not set any default sizes for specific applications.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. For me this was just the default behavior after activating the extension. I set my preferred hotkeys for tiling, which work great for every application except the terminal, which shows small gaps on the sides when snapped to certain regions.

## Context

Trying to snap terminal windows.

## Your Environment

* gnome-shell version: [3, 28, 4]
* affected application(s) (e.g. chrome, nautilus, all, ...) Just the terminal.
* distribution: Ubuntu 18.04

**Comment by negesti** [comment]
i guess it's the gnome-terminal? The terminal window can not be resized to "every pixel" only to row height, you can try that with mouse resize too
