### ISSUE TITLE
latest version broken on my system

### ISSUE THREAD

**Issue by sdanieru** [negesti/gnome-shell-extensions-negesti#167]
## Expected Behavior
Put Windows should continue working after update

## Current Behavior
The latest update is completely broken on my system

## Steps to Reproduce (for bugs)
1. Install latest Put Windows version
2. 
3.
4.

## Context
The extension is completely broken; doesn't function at all. In the extensions list, when I uninstall and try to reinstall, it just says 'Error'.

## Your Environment

* gnome-shell version: 3.28.4
* affected application: Put Windows
* distribution: Ubuntu 18.04.3 LTS

**Comment by negesti** [comment]
Fixed together with #166
