### ISSUE TITLE
not work configuration with manjaro gnome 3.34

### ISSUE THREAD

**Issue by garvied** [negesti/gnome-shell-extensions-negesti#170]
The settings of extension putWindow@clemens.lab21.org had an error:
```
Error: Requiring Wnck, version none: Typelib file for namespace 'Wnck' (any version) not found
```

Stack trace:
```
@/home/javier/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:7:7
get prefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:675:13
_showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:13
_extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:320:13
_scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:298:13
asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
@<main>:1:43
```

**Comment by negesti** [comment]
you require libwnck to open the settings dialog

> For application based configuration the extension relies on the X11 library wnck.
> 
>     Suse: sudo zypper in libwnck-devel
>     Arch: pacman -S libwnck3
>     Fedora:
>         sudo yum install libwnck3
>         sudo dnf install libwnck3
>     Debian/Ubuntu: apt-get install gir1.2-wnck-3.0
> 
> Because of this dependency and the different concepts of wayland and X11 to identify > applications (wm_class vs. application_id) Wayland is not supported!

**Comment by garvied** [comment]
Thanks, after install ir work ok.
Great extension
