### ISSUE TITLE
Moving applications to target workspace ignored

### ISSUE THREAD

**Issue by WolfeWorks** [negesti/gnome-shell-extensions-negesti#172]
## Expected Behavior
Setting a workspace number in the preferences Applications tab and clicking the save button should set the workspace the selected application opens in and the workspace number should display the next time the Applications tab is opened in a newly opened preferences window.

## Current Behavior
The workspace selection always reverts to '0' after closing the preferences window for all applications no matter how they were previously set & saved individually. Opening the applications always opens them in the current workspace rather than the specified workspace. dconf shows that the workspace number is set in the current value for the targetWorkspace for each application. 'Move window to workspace when created' is on as is 'Auto-Move window when created' and 'Enable move to workspace' (in the General tab). Nothing else has been changed in the preferences and the workspaces exist.

## Steps to Reproduce (for bugs)

1. Start an application, e.g. Firefox, in a workspace, e.g. 2
2. Open the putWindow preferences and turn on 'Enable move to workspace' in the General tab if not already on, then select the Applications tab.
3. Click the '+' button and select the application, e.g. Firefox.
4. With Firefox highlighted, turn on 'Move window to workspace when created' and select the desired 'Window Target Workspace', e.g. 3.
5. Turn on 'Auto-Move window when created'.
6. Click the green save button at the bottom of the window, then exit the preferences window.
7. Exit the application, e.g. Firefox.
8. Change to a third workspace, e.g. 1.
9. Start the application, e.g. Firefox. It should open in the target workspace, e.g. 3. If it starts in the current workspace, e.g. 1, putWindow failed.
10. Open the putWindow preferences again and select the Applications tab.
11. Select the application, e.g. Firefox, and if the 'Window Target Workspace' is not 3, putWindow failed.

## Your Environment
Ubuntu 18.04

* gnome-shell version: 3.28.2
* affected application(s) (e.g. chrome, nautilus, all, ...)
Tried with Gnome-terminal, Firefox, Thunderbird, LibreOffice-calc
* distribution putWindow 26

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
