### ISSUE TITLE
Move to upper right corner using Super+Up+Right and so on?

### ISSUE THREAD

**Issue by tonsV2** [negesti/gnome-shell-extensions-negesti#174]
As the title indicate, is there a way to assign a combo of arrow keys so Up+Right moves to upper right corner, Down+Right moves to lower right corner and so on? For a keyboard, as on most laptops, without a numeric key button section, that would be nice.

**Comment by negesti** [comment]
You can try "intelligent Corners".

**Comment by tonsV2** [comment]
Thanks, I've needed this for years.
