### ISSUE TITLE
Move two windows accordingly

### ISSUE THREAD

**Issue by Dolland** [negesti/gnome-shell-extensions-negesti#175]
When i place two windows side by side and go to resize one, the other windows doesn't resize accordingly.
## Expected Behavior
That make a lot of sense that i can resize two side by side windows together, like gnome currently does by default.

* gnome-shell version: 3.34
* distribution: Ubuntu 19.10

**Comment by negesti** [comment]
That's the expected behaviour. The extension only moves the selected window.
