### ISSUE TITLE
Windows within the app itself utilize same Put settings

### ISSUE THREAD

**Issue by hallmerle** [negesti/gnome-shell-extensions-negesti#176]
##  Expected Behavior
In Shotwell, when viewing an image there are options for changing that image - Rotate, Crop, Straighten, Red-Eye, Adjust, Enhance.  Each of these opens a small dialog box  with settings you can change.

## Current Behavior
After adding Shotwell to the Put Windows settings, any of the tool dialog boxes also use the same Put Windows settings instead of remaining a small dialog box.

## Possible Solution
I don't know the terminology, but maybe have Put Windows ignore subwindows/dialog boxes?

## Steps to Reproduce (for bugs)
1. Open Shotwell and Put Windows
2. Add Shotwell to Applications and adjust the settings. Save settings.
3. Reopen Shotwell and open an image
4. Select any of the image tools at the bottom of the image.  The tool will display the same size as the Shotwell window and cover up the image entirely

## Context
Trying to set the Shotwell window size and position.  Did not expect the tool dialogs to take on the same settings.

## Your Environment
* gnome-shell version:  3.28.4-0ubuntu18.04.3
* affected application(s) So far, only discovered in Shotwell 0.28.4
* distribution  3.28.4-0ubuntu18.04.3
![shotwell_put_settings](https://user-images.githubusercontent.com/63920727/79644168-bf0d6a80-816c-11ea-9e9f-7d754d0cc806.jpg)
![shotwell_after_put](https://user-images.githubusercontent.com/63920727/79644169-bfa60100-816c-11ea-8313-92244e47de49.jpg)
![shotwell_normal](https://user-images.githubusercontent.com/63920727/79644171-bfa60100-816c-11ea-9353-c295875f6e13.jpg)

**Comment by negesti** [comment]
Thank you for you detailed description. Unfurtionatly I used the "wm class" property for the app based settings which is the same for all windows including "popups". Up until know I only knew that gimp opens the multiple windows. 

Afaik a fix is not possible. Changing this would require a complete rewrite of the app based settings, but I don't have the time for that, sry.

**Comment by hallmerle** [comment]
I understand.  No worries.  I didn't see it as an issue when I searched so
figured there wasn't any harm in asking.  Maybe something in the
description or help text to say that it won't work with applications that
use multiple windows, etc., would be helpful.  Just a thought.

I appreciate your response.

Merle

**Comment by negesti** [comment]
Closing this, as application based config is no longer supported by this extension in gnome-shell v46
