### ISSUE TITLE
Error loading the preferences dialogue

### ISSUE THREAD

**Issue by ThomasPak** [negesti/gnome-shell-extensions-negesti#178]
## Expected Behavior

On the gnome shell extensions webpage, when I click the button "Configure this extension" for Put Windows it should open the preferences dialogue.

## Current Behavior

Instead of a preferences dialogue, a pop-up window comes up with the message `There was an error loading the preferences dialogue for Put Windows:`, followed by the error message

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/thomas/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:1028:3
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```

## Steps to Reproduce (for bugs)

1. Install "Put Windows" extension at https://extensions.gnome.org/extension/39/put-windows/
2. Go to installed extensions at https://extensions.gnome.org/local/
3. Click on the "Configure this extension" button

## Context

The shortcuts for Put Windows suddenly stopped working when I logged into my computer today. Hence, I thought something went wrong with the keybindings and I wanted to fix it in the preferences dialogue, but it gave me the error message above instead. Perhaps the latest update broke the extension.

## Your Environment

* gnome-shell version: 3.28.4
* Ubuntu 18.04

**Comment by negesti** [comment]
@ThomasPak can you try the current develop version?

**Comment by ThomasPak** [comment]
@negesti I tried with the current develop version and it gave me a similar error:

```
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/thomas/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:1027:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  
```

**Comment by negesti** [comment]
my fault, i didn't remove the ! after my local tests... can you please try again?

**Comment by ThomasPak** [comment]
I tried again and now the preferences dialogue opens successfully. However, the keyboard shortcuts don't do anything (I only use Move to top/bottom).

**Comment by negesti** [comment]
ok, i will download Ubuntu 18.04..

**Comment by negesti** [comment]
@ThomasPak  new version should work now

**Comment by RDeckard** [comment]
@negesti It works, many thanks!

**Comment by negesti** [comment]
Fixed with Release v29 (github release). WIll be available on extensions.gnome.org after review

**Comment by ThomasPak** [comment]
@negesti Yup, works perfectly now. Thanks so much. :pray: :pray:
