### ISSUE TITLE
Multi monitor edge positioning is wrong for primary monitor leading to hidden window parts

### ISSUE THREAD

**Issue by moritzaugustin** [negesti/gnome-shell-extensions-negesti#180]
First I would like to thank for the very nice extension which makes very fun to work with and boost productivity. 

When using in my monitor setup (three screens: too large monitors and below a laptop screen), there is a problem when moving windows to the screen edges using "Put Windows" via hot keys as shown in the attached screenshot: 
* For the non-primary screens everything works fine (green encircled screens). 
* However, for the primary monitor (red encircled screen, you can see the gnome bar in the top) the lower two windows are positioned wrongly as described in the attached screenshot. The crucial part is not the gap to the upper windows (minor bug) but the hidden parts of the windows in the very bottom (where the red font is in the attached figure). 

It would be great if this bug could be addressed and if I can help please let me know how. 

![multi_monitor_window_parts_lost](https://user-images.githubusercontent.com/4638480/95057421-6fa8ff80-06f6-11eb-8186-57562b85d37f.png)

**Comment by negesti** [comment]
have you tried "Always ignore top panel"?

**Comment by moritzaugustin** [comment]
That exactly solved the issue! Many thanks.
