### ISSUE TITLE
Fix for 3.38

### ISSUE THREAD

**Issue by pedropedigoni** [negesti/gnome-shell-extensions-negesti#181]
For work in Gnome 3.38, edit moveFocus.js.

Change the line:
**const Tweener = imports.ui.tweener;**
to
**const Tweener = imports.tweener;**

Source: a comment by pemmoura at [https://extensions.gnome.org/extension/1268/gnomesome/
![Captura de tela de 2020-10-13 18-06-30](https://user-images.githubusercontent.com/72826658/95916438-ff961b80-0d7e-11eb-81ea-fd7d1d035d88.png)
](url)

**Comment by negesti** [comment]
I'm not using gnoem 3.38 yet. Can you test the fix and provide a PR?
To make sure everything works with older gnome versions, something like should work
```
if (imports.tweener) {
   const Tweener = imports.tweener;
} else {
  const Tweener = imports.ui.tweener;
}
````
