### ISSUE TITLE
Feature request: 3x3 grid

### ISSUE THREAD

**Issue by JFK24** [negesti/gnome-shell-extensions-negesti#183]
## Expected Behavior

Position windows with shortcuts or mouse on a 3x3 grid, additionally to the current behaviour. 

## Current Behavior

Position windows with shortcuts or mouse on a 2x2 grid or center and full screen.

## Context

It would improve working on a big screen such as 4K 32" monitor

## Your Environment

* gnome-shell version: 3.36.4
* affected application(s) (e.g. chrome, nautilus, all, ...): all
* distribution: Ubuntu 20.04

**Comment by negesti** [comment]
that would require a lot of work, and is no real use case for me. Have you tried gTile?
Using the "Center Width & Height" settings, you can move a window to the center using different width and height and then move it up or down. No real 3x3 grid but maybe a workaround

**Comment by JFK24** [comment]
I'll try your suggestions, thanks!
