### ISSUE TITLE
Left / Right Move Focus in Multi-Monitor setup broken on 3.36.4

### ISSUE THREAD

**Issue by compleatang** [negesti/gnome-shell-extensions-negesti#185]
This is a great extension. I have been a user for a long time. 

In:

```
gnome-shell --version
GNOME Shell 3.36.4
```

(ubuntu 20.04)

I'm no longer able to shift focus left or right via keyboard shortcut since updating to latest published version of the Put Windows extension

## Expected Behavior

I should be able to trigger my keyboard and have the focus shift to the left or right monitor.

## Current Behavior

Nothing happens

## Steps to Reproduce (for bugs)

1. gnome shell on version above
2. put windows extension on `"version": 31` per the metadata.json
3. turn on left/right focus 
4.trigger assigned keyboard shortcuts

**Comment by compleatang** [comment]
I'm happy to help debug but I'm not sure what logs would be relevant to debugging (or how to get them).

**Comment by negesti** [comment]
I guess it's the animation of moveFocus. Can you update to the current develop version or fix the "import" in moveFocus.js?
```
   const Tweener = imports.tweener.tweener || imports.ui.tweener;
```

**Comment by compleatang** [comment]
@negesti editing moveFocus with the updated import solves the problem and it's back to working normally now. Thanks! 

FWIW, I run a pretty stock Ubuntu LTS so this could potentially affect quite a few users.
