### ISSUE TITLE
extensions.gnome.org : current update failed (if Gnome Shell is not reloaded via console)

### ISSUE THREAD

**Issue by MTindev** [negesti/gnome-shell-extensions-negesti#186]
## Expected Behavior

This Nov 4, 2020, be able to update the gnome extension via https://extensions.gnome.org/ at this date/time, wtihout error.

## Current Behavior

This Nov 4, 2020 :
Updating the extension triggers a "ERROR" red label, and the extension does not work anymore. 
Uninstalling and installing it back keeps the active error.

## Possible Solution

Shortcut ALT+F2  then type "r", to reload the Gnome environnement. Then you can (re)install the extension without error.

## Steps to Reproduce (for bugs)

1. Go to https://extensions.gnome.org/local/
2. If there is an update (green icon) click this "update" button
3. "ERROR" is displayed near the icon : the update has failed and the extension does not work anymore

## Your Environment

* gnome-shell version : 3.36.3
* affected application(s) (e.g. chrome, nautilus, all, ...)
* distribution : Ubuntu 20.04 LTS

**Comment by negesti** [comment]
twinner import problem fixed in v32

**Comment by negesti** [comment]
twinner import problem fixed in v32
