### ISSUE TITLE
Is it possible in Put Windows in the menu configuration called Applications add a "Always on Top" checkBox to set it when a configured app is started?

### ISSUE THREAD

**Issue by andrehtgti2** [negesti/gnome-shell-extensions-negesti#188]
Is it possible in Put Windows 

in the menu configuration called Applications (Application based size and location setting, that allows you to move windows on startup or circle betwen multiple configured locations)

add a "Always on Top" checkBox 
to set it when a configured app is started?

Thank you!

Very Nice Extensio! Very useful!

**Comment by negesti** [comment]
Whole application based configuration will be removed as does not work with wayland and would require a complete re-write
