### ISSUE TITLE
Opening settings results in `No property margin_left on GtkLabel` error

### ISSUE THREAD

**Issue by pdecat** [negesti/gnome-shell-extensions-negesti#193]
When opening settings on Ubuntu 21.10 current beta with a Gnome on Xorg session, a `No property margin_left on GtkLabel` error happens.

This is with current development head:

```
# cd ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org
# git log -n 1
commit a8de0b5c9f2269acdd7020ef3f775e6213245872 (HEAD -> develop, upstream/develop, upstream/HEAD, origin/develop)
Author: negesti <clemens@lab21.org>
Date:   Tue Apr 13 18:02:23 2021 +0200

    dont import wnck in 'header'
```

## Expected Behavior

Settings should open normally.

## Current Behavior

Trying to open Settings fail:

![image](https://user-images.githubusercontent.com/318490/136183615-ad11f26b-ee75-4ed5-9d0e-7909534debd6.png)

> The settings of extension putWindow@clemens.lab21.org had an error:
> ```
> Error: No property margin_left on GtkLabel
> ```
> 
> Stack trace:
> ```
> _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
> _generateMainSettings@/home/patrick/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:114:16
> wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
> _init@/home/patrick/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:38:27
> wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
> buildPrefsWidget@/home/patrick/.local/share/gnome-> shell/extensions/putWindow@clemens.lab21.org/prefs.js:1037:16
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> start@resource:///org/gnome/gjs/modules/script/package.js:190:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

## Steps to Reproduce (for bugs)

1. upgrade Ubuntu to current 21.10 beta ([final is supposed to release on October 14, 2021](https://discourse.ubuntu.com/t/impish-indri-release-schedule/18540))
2. open Extensions
3. click the gear next to "Put Windows" extension
4. get _Something's gone wrong_ message
5. click _Technical details_ to see the stack trace

## Context

It used to work fine on Ubuntu 21.04 with Gnome 3.38.

## Your Environment

* gnome-shell version: `40.5-1ubuntu2`
* affected application(s): N/A
* distribution: Ubuntu 21.10 current beta

**Comment by negesti** [comment]
gnome-shell 40 uses GTK 4 and includes a major rewrite aka. the extension does not work with gnome-shell >= 40
(duplicates #191)
