### ISSUE TITLE
[INCOMPATIBLE] Put Windows - are there any efforts to make it compatible with Ubuntu 21.10 ?

### ISSUE THREAD

**Issue by LeadManPL** [negesti/gnome-shell-extensions-negesti#196]
[Put Windows](https://extensions.gnome.org/extension/39/put-windows/) extension is incompatible with Ubuntu 21.10 . Are there any efforts to make it compatible?

**Comment by negesti** [comment]
but Gnome Shell 40 and 41 partly work, at least if you use the github version. 
Settings will work but does not look nice with 40+, the even if you use version. Wayland is not really supported.

Basically you can add your ```gnome-shell --version``` to metadata.json and it should work

**Comment by negesti** [comment]
duplicate #194

**Comment by LeadManPL** [comment]
Thanks for the explanation. In the mean time I found almost the same tool:  [Awesome Tiles](https://extensions.gnome.org/extension/4702/awesome-tiles/)
The obnly drawback is it maximizes window on Super+KP_5 , but not unmaximizes on pressing it again :/
