### ISSUE TITLE
gjs-1.71 (+ patch)

### ISSUE THREAD

**Issue by freddyw** [negesti/gnome-shell-extensions-negesti#197]
gjs 1.71 introduced a check on GObject classes (https://mail.gnome.org/archives/commits-list/2019-September/msg00008.html), which this extension does not pass.

## Current Behavior
JS ERROR: Extension putWindow@clemens.lab21.org: TypeError: Object 0x37f601c93028 is not a subclass of GObject_Object, it's a Object

## Possible Solution
See attached patch

## Your Environment
* gnome-shell version 41/42
* Fedora 35/36

[gnome-shell-extension-put-windows-gobject.zip](https://github.com/negesti/gnome-shell-extensions-negesti/files/8333866/gnome-shell-extension-put-windows-gobject.zip)

**Comment by negesti** [comment]
thanks for the patch, can you provide the changes as pull request?

**Comment by freddyw** [comment]
For completeness sake, I created a PR: https://github.com/negesti/gnome-shell-extensions-negesti/pull/198
