### ISSUE TITLE
How to install it with Gnome Tweak Tool? I don't see any installation options.

### ISSUE THREAD

**Issue by o771e** [negesti/gnome-shell-extensions-negesti#202]
The easiest way to install is to download the latest release zip from the [releases](https://github.com/negesti/gnome-shell-extensions-negesti/releases) page and install it using the gnome-tweak-tool.

How to do this?

**Comment by negesti** [comment]
hm, looks like this was remove from gnome-shell.
i have created a symlink in ``.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org`` that points to the git repo.
