### ISSUE TITLE
Obtain saved config as a file

### ISSUE THREAD

**Issue by michael-hoss** [negesti/gnome-shell-extensions-negesti#204]
## Expected Behavior

I would like to obtain the file where the config of Put Windows is stored.

## Current Behavior

Currently, by looking at the GUI (and a bit at the source code), I have not found where the settings are stored. 
I also went into https://gitlab.gnome.org/GNOME/gnome-shell/blob/main/js/misc/extensionUtils.js#L213 but don't seem to find the path where this is stored. 

## Possible Solution

Could someone who knows where the config is stored either just tell me, or even include into the tooltip of the "Save" Button for Applications config?

I expect that somewhere, there is something like a `~/.putwindows` with both the normal config and the "Applications" config.

## Context

I want to git-track that config file to avoid having to set the configs manually in the GUI again once I set up a new machine, and potentially share my config with others. I am tracking my home directory in git, too, where I also track .bashrc and other dotfiles. 

## Your Environment

* gnome-shell version: GNOME Shell 3.36.9
* affected application(s) (e.g. chrome, nautilus, all, ...)
* distribution Ubuntu 20.04

**Comment by negesti** [comment]
Not sure this will work, the setings are store in dconf
```dconf  list /org/gnome/shell/extensions/org-lab21-putwindow/```

**Comment by michael-hoss** [comment]
Thank you, I guess `dconf dump` and `dconf load` are what I am looking for
