### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by swebb** [negesti/gnome-shell-extensions-negesti#206]
## Expected Behavior

It works

## Current Behavior

The extension fails to start with the following error:

> import declarations may only appear at top level of a module

## Possible Solution

I think this is caused by [Gnome switching from it's import system to ESM modules](https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/).

There could quite likely be other incompatible changes, but that's the most obvious.

## Steps to Reproduce (for bugs)

Try to install the extension in Gnome 45 (e.g., Fedora 39).

## Your Environment

* gnome-shell version: 45.1
* affected application: Extensions
* distribution: Fedora 39

**Comment by negesti** [comment]
Yes, looks like v45 comes with multiple breaking changes. As the app configuration does not work (since ~ v41) the extension requires a bigger cleanup/refactoring to work properly with v45

**Comment by ehud-gordon** [comment]
Thanks for your Extension. Do you know how to achieve this beahvior in v45 / alternative extension that offers this beahvior?

**Comment by negesti** [comment]
see #208, gnome 45 will not be supported
