### ISSUE TITLE
Hot corner activation (drag a window to resize to the adjacent quadrant of the screen)

### ISSUE THREAD

**Issue by v-ko** [negesti/gnome-shell-extensions-negesti#48]
With a moths delay (after posting about it on extensions.gnome.org) I'm opening the issue to discuss an idea - to add a feature to resize windows not only by shortcuts , but  with moving to the corners and sides too. Simple example : drag a window to the top left corner , and it resizes to the top left quadrant of the screen . Much like now dragging to the left or right side resizes a window to the left or right half of the screen .
 I will try to write the code myself , but first I want to get some feedback on the idea + any tips on where to integrate it with the existing code.

**Comment by Nestak2** [comment]
are there any news regarding this? it would be really nice to have these functionalities

**Comment by negesti** [comment]
hi, I'm not planning to add implement this feature.
