### ISSUE TITLE
Disable Resize

### ISSUE THREAD

**Issue by negesti** [negesti/gnome-shell-extensions-negesti#53]
from extensions.gnome.org

---

dotsdl:
Hey Nesta, thanks for the fantastic extension! This makes my Compiz withdrawals bearable in GNOME. I do have one request: could you add an checkbox option to NEVER change the size or proportions of windows on move? That's the behavior I remember from Put on Compiz, and it was useful given that some windows just don't scale as well as others. Excellent stuff!

---

Nesta: 
For "move to corner" you can already set this (Settings-Main-Moving to corner). Do you want to completely disable resize or on a per app base?

---

**Comment by mihaic** [comment]
Any chance you will reconsider this feature request? I am also used to the Compiz Put way of moving windows around without resizing them.
