### ISSUE TITLE
Notify on conflicts with main settings.

### ISSUE THREAD

**Issue by Psykar** [negesti/gnome-shell-extensions-negesti#56]
I was about to report a bug, but realized it was due to a conflict with the default gnome bindings.
Is it possible to notify when a setting conflicts with a default gnome binding? Causes strange issues otherwise (eg. Super left assigned to move to left, but also assigned to the main setting 'view split on left')

**Comment by paller** [comment]
I don't know much about Gnome-Shell extension java script, so I might be wrong here.

I have the impression it is possible to achieve almost the same through java script as using the Gnome C libraries. Using Glib-2.0 and Gio it is easy to get a list of keys for any schema and the associated key-bindings for each of them. If the same is possible in a Gnome-Shell extension it would be possible to search for already used key-bindings and give a warning, even let the user those to clear the other binding.

I have made the C code for listing key-bindings (just like the 'gsettings' cli) and it shouldn't be hard to port, if it is possible to do the same in an extension script?

**Comment by negesti** [comment]
extensions use dconf. At the moment the extension only uses Gio.Settings and Gio.SettingsSchemaSource and not all C methods are available in javascript.

Maybe you can share your code and can test this. Or you test it with looking glass ;)

**Comment by paller** [comment]
In serious lack of documentation for the java script part, this is how far I got.

```javascript
const Gio = imports.gi.Gio;
const Glib = imports.gi.Glib;

let gs = new Gio.Settings({schema: "org.gnome.desktop.wm.keybindings"});
let kl = gs.list_keys();

Glib.printf(kl);
```

Can't find any Fedora package that provides Glib, so the call to print is just imaginary. However, the C code below will output the list of keys with all their associated keybindings.

$ gcc -Wall gset.c $(pkg-config --cflags gio-2.0 --libs gio-2.0) -o test          
```c
#include <gio/gio.h>
#include <glib.h>
#include <glib/gprintf.h>

int
main (int argc, char **argv)
{
	GSettings *gs;
	gchar    **ss;
	gchar    **gv;

	gs = g_settings_new("org.gnome.desktop.wm.keybindings");
	ss = g_settings_list_keys(gs);
	
	for (gchar *s = *ss, **t = ss; s != NULL; s = *(t++))
	{
		gv = g_settings_get_strv(gs, s);
		g_printf("%-30s : ", s);	

		for (gchar *kl = *gv; kl != NULL; kl = *(gv++))
		{
			g_printf("%s\t", kl); // Compare this with the users newly requested keybinding.
		}

		g_printf("\n");
	}

	g_strfreev(ss);

	return 0;
}
```

I hope it helps you.

**Comment by paller** [comment]
Do you think it is doable?

If you can point my in a direction with the javascript I would like to give it another try.

The call to `Gio.Settings({schema: "org.gnome.desktop.wm.keybindings"});` is deprecated, but I'm not sure how to make the call correctly. How do you translate the C libs into the corresponding javascript functions?

**Comment by negesti** [comment]
Documentation for javascript does not really exist. As far as i know, the default keybinding are stored in "org.gnome.desktop.wm.keybindings" and "org.gnome.mutter.keybindings". 

e.g. it should be possible to get the settings source object using

      Gio.SettingsSchemaSource.get_default().lookup("org.gnome.desktop.wm.keybindings", false)
      Gio.SettingsSchemaSource.get_default().lookup("org.gnome.mutter.keybindings", false)

After you have the SchemaSource, create a SchemaObject using: 
       let gnomeSettings = new Gio.Settings({settings_schema: schemaSource})
       gnomeSettings.list_keys()

Simple statements can be testing using LookingGlas (alt + f2 : lg). Here you can inspect the javascript object. Once we figured out how to test for conflicts, the Gtk.CellRendererAccel in prefs.js needs to check for conflicts in the 'accel-edited' signal callback. 

I will look into this, when I have more time at work :)

**Comment by negesti** [comment]
Anyone tested this?

**Comment by crittico** [comment]
I didn't get into the code but just as a test case, I had problems due to conflicts with gnome keybindings and after this commit they seem all gone.
