### ISSUE TITLE
Incompatible with bottom panel

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [negesti/gnome-shell-extensions-negesti#66]
When bottom panel is installed the Windows are still put as if the panel would be in top.

**Comment by negesti** [comment]
Found a way to check, if the extension is installed and active: 

     let extension = imports.misc.extensionUtils.extensions["Bottom_Panel@rmy.pobox.com"];
     if (extenstion.state == 2) {
        //active
     }

first problem solved :)
