### ISSUE TITLE
Issue with application placement in gnome 3.14 and incompatiblity with title bar removal of left/right tiled windows

### ISSUE THREAD

**Issue by ioqzc** [negesti/gnome-shell-extensions-negesti#70]
These are two separate issues, sorry if I am am supposed to open two separate bugs :baby: I guess these are related to using this fresh version of gnome.

This happens in Fedora 21(Gnome 3.14) using a single screen(on my laptop).

What I Want(WIW): To have a titlebar-less "Transmission" automatically put on the right side of the screen.

What I did:
1. I installed "Put Windows" extension(PWe, if I may) and added Transmission in the extension's settings, like this: in "Applications", set "Auto-Move window when created" to "On", "width" to "50", "Height" to "100", X-Position to "50", "Y-Position" to "0".
2. I noticed that neither Transmission's window, neither any other window I tried is placed as defined in PWe(with the settings as described above or any other I tried); I did a debug and I modified the file extension.js:
I changed the line:
    } else if (!win.skip_taskbar) {
to
      } else if (win.skip_taskbar) {
I have no idea what "skip_taskbar" means, but it solved the issue I had.
3. I also want to remove the title bar of all maximized windows so I installed "Maximus Two" from the gnome extensions page. Also tried it's latest version from git. I also tried "Method 2: editing the [Adwaita] theme" from "http://www.webupd8.org/2011/05/how-to-remove-maximized-windows.html". With all I have *the same issue* regarding WIW: If I put Transmission to the right by tiling it with "Super+Right" the title bar disappears, as expected. **But if I use PWe, though the window is put on the right half of the screen(that is like a right-side tile), it's titlebar is still shown**... this is unexpected; I also had a peak in the code there and, if the height is set to 100(as it is now) maximize() is called on the window with MaximizeFlags.VERTICAL, as I guess it should; this one beats me...

**Comment by negesti** [comment]
sry for the late response...

To get it right:
1. the auto move feature works after replacing win.skip_taskbar
2. title bar is not removed (Maximus Two extension)

**Comment by ioqzc** [comment]
Yep

**Comment by negesti** [comment]
maximus 2 works with maximized windows. Tiled windows are not considered maximized and the titlebar is not removed. Can not reproduce any miss placement.
