### ISSUE TITLE
Gnome 3.8 Error

### ISSUE THREAD

**Issue by tsquillario** [negesti/gnome-shell-extensions-negesti#71]
Have to use CentOS 7, testing some extensions. This seems like a similar issue  https://github.com/azdyb/gnome-shell-extension-cpufreq/pull/4/files?short_path=88b99bb 

If I get some time I'll work on it and send a pull request!

gnome-session: JS LOG: Extension "putWindow@clemens.lab21.org" had error: TypeError: imports.misc.config.PACKAGE_VERSION.startsWith is not a function

CentOS Linux release 7.0.1406 (Core)
gnome-shell-3.8.4-32.el7_0.x86_64

**Comment by tsquillario** [comment]
Line 22 in moveFocus.js needs updated as well :)

**Comment by negesti** [comment]
true, should work now
