### ISSUE TITLE
Error Loading Preferences Dialog

### ISSUE THREAD

**Issue by siddharthist** [negesti/gnome-shell-extensions-negesti#72]
When using Gnome Tweak Tool or extensions.gnome.org to attempt to access the preferences for this extension, a dialog window pops up with the following message:

There was an error loading the preferences dialog for Put Windows:
Error: Requiring Wnck, version none: Typelib file for namespace 'Wnck' (any version) not found
```
Stack trace:
  @/home/lb/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/prefs.js:7
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:80
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1
  ```
![screenshot from 2015-03-11 15 16 15](https://cloud.githubusercontent.com/assets/4294323/6608151/d27b7d66-c801-11e4-9c7c-f6e71c224610.png)

**Comment by siddharthist** [comment]
Here's a better screenshot
![screenshot from 2015-03-11 15 16 15](https://cloud.githubusercontent.com/assets/4294323/6608145/c87b25dc-c801-11e4-8332-f5e8452139f4.png)

**Comment by negesti** [comment]
you need to install ibwnck, in most cases it's installed with gnome-shell. 

on my fedora 21 its: 

        $ yum list installed | grep wnck
        libwnck.x86_64                          2.31.0-4.fc21                  installed
        libwnck3.x86_64                         3.4.9-1.fc21                   installed

**Comment by negesti** [comment]
i know it was somewhere in the wiki. see [here](https://github.com/negesti/gnome-shell-extensions-negesti/blob/30b3deb610e1b9a97bfe608d0301ee32f507fd78/README.md#wnck)

**Comment by siddharthist** [comment]
Awesome. I don't think I can resolve this issue, but it is working for me now. Thank you!

**Comment by negesti** [comment]
Which distribution and gnome-sell version do you use?

**Comment by siddharthist** [comment]
Arch Linux, GNOME Shell 3.14.3.

On Fri, Mar 13, 2015 at 3:40 AM, negesti <notifications@github.com> wrote:

> Which distribution and gnome-sell version do you use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/negesti/gnome-shell-extensions-negesti/issues/72#issuecomment-78910753>
> .
>



-- 
Langston Barrett || email <langston.barrett@gmail.com> || cell: +1
(314)-598-5680
