### ISSUE TITLE
Gnome 3.16 compatibility

### ISSUE THREAD

**Issue by zara86** [negesti/gnome-shell-extensions-negesti#74]
On Gnome 3.16, PutWindows stop working even if "3.16" was added to metadata.json.
Il looks like a problem with "KeyBindings" function, but i'm not sure.

**Comment by negesti** [comment]
i'm still on 3.14 with my fedora system.

which distribution do you use? has in 3.16 installed out of the box?

**Comment by 73** [comment]
The live-cd is out:
https://www.gnome.org/getting-gnome/

**Comment by zara86** [comment]
Some functions are being renamed essentially. I made a pull request BUT it need to be tested on older gnome before because I'm not sure that "get_frame_rect" function was present before gnome 3.16

**Comment by negesti** [comment]
Thanks!
i created a feature branch for gnome-shell 3.16. once it's working with 3.16 i will check <= 3.14 compatibility and merge it back into develop

**Comment by zara86** [comment]
It works on my 3.16. A friend of mine have tested it on 3.14 and it seem work fine there too, but you would need a further and more thorough testing.
Can't say anything on movefocus feature, because i'm not using it, but the moving/resizing windows it's ok.

I can't test it on older versions (<3.14) unfortunately, so I hope that someone can testing it.

**Comment by Velho** [comment]
It works fine except some anomalieṣ with double screen where the other screen has bigger resolution. Dunno if this occurs on other versions aswell.

**Comment by negesti** [comment]
I just upgraded to Fedora 22 which comes with 3.16
The develop branch works with 3.16, including move focus.
