### ISSUE TITLE
Error Installing Extension GNOME 3.4.2

### ISSUE THREAD

**Issue by moshmage** [negesti/gnome-shell-extensions-negesti#76]
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
GNOME Shell 3.4.2    

---
Installing the extension from extentions.gnome.... says "error";
I tried all that was in https://github.com/negesti/gnome-shell-extensions-negesti/issues/73 still no fun.

When I try to Super+Shift+Right (snapped or unsnaped) on a Terminal all I see is `C`

When I open gnome-tweak-tool PutWindows is not even on the list.
When I open https://extensions.gnome.org/local/ PutWindows is not listed
Follows the log when I did `gnome-shell --replace &` (I also tried the Alt+F2, r, enter - no fun)

```
@~/gnome/gnome-shell-extensions-negesti{}> gnome-shell --replace &
[1] 15595
@~/gnome/gnome-shell-extensions-negesti{}>     JS ERROR: !!!   WARNING: 'assignment to undeclared variable signalId'
    JS ERROR: !!!   WARNING: file '/usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com/extension.js' line 124 exception 0 number 156
      JS LOG: GNOME Shell started at Tue Apr 21 2015 14:56:57 GMT+0100 (WEST)
Window manager warning: Log level 16: STACK_OP_REMOVE: window 0x75 not in stack
WARNING : Testing for expected AutostartCondition failed: Got (None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gtweak/utils.py", line 152, in uses_autostart_condition
    return asc.split(" ", 1)[0] == autostart_type
AttributeError: 'NoneType' object has no attribute 'split'

(gnome-tweak-tool:15633): Gtk-CRITICAL **: gtk_widget_get_preferred_height_for_width: assertion `width >= 0' failed
```
The line `(gnome-tweak-tool:15633): Gtk-CRITICAL **: gtk_widget_get_preferred_height_for_width: assertion `width >= 0' failed` keeps repeating on-and-on.

**Comment by negesti** [comment]
hm can you disable native-window-placement the first js error comes from this extension

**Comment by moshmage** [comment]
@negesti sorry about the late reply, I should have read that log in its entirety. Anyway, here's the log now:

```
File "/usr/lib/python2.7/dist-packages/gtweak/utils.py", line 152, in uses_autostart_condition
    return asc.split(" ", 1)[0] == autostart_type
AttributeError: 'NoneType' object has no attribute 'split'
```

The error about assertion is still there.
Now I am able to see it on the Extensions list, both on extensions.gnome.... and on gnome-tweak-tool but when I activate the extension, close the gnome-tweak-tool or refresh the page, and the extension is not active anymore.

I'd send logs your way, but I have no clue on what logs you need :(

**Comment by negesti** [comment]
any news?

**Comment by moshmage** [comment]
@negesti I made a full clean install, turns out I had some weird version of GNOME; Now I have everything up and runing :) Thanks for caring :)

**Comment by negesti** [comment]
i like "self fixing bugs" :)
