### ISSUE TITLE
Workspace Support

### ISSUE THREAD

**Issue by micahthomas** [negesti/gnome-shell-extensions-negesti#78]
Would be great to have support for moving windows to specific workspaces also.

**Comment by negesti** [comment]
There is an "kind of official" extension for that:
https://extensions.gnome.org/extension/16/auto-move-windows/

**Comment by micahthomas** [comment]
@negesti Thanks for the suggestion. I tried it. 

It doesn't seem to have the same app detection you are using, because most of my desktop apps dont show up inside the options. I have raised an issue on their extension page. 

Is there anything against implementing the feature using your extension?

**Comment by negesti** [comment]
haven't looked into it but should be possible. But I can not tell you when i will find the time to do it

**Comment by micahthomas** [comment]
@negesti Alright, sounds good. If I get time I'll look into it also.

**Comment by negesti** [comment]
i created a feature branch. After enabling "move to workspace" in main settings, you can set the target workspace in the "applications" sections

**Comment by fastrizwaan** [comment]
ctrl+alt+shift up/down keys, Also Shift+Super+pageUp and pageDown keys move the current window in the workspace to up or down. It's part of gnome shell 3.16
![screenshot from 2015-09-05 10-54-52](https://cloud.githubusercontent.com/assets/1161682/9697853/a5cd7d72-53bc-11e5-8925-be875c5e3579.png)

**Comment by negesti** [comment]
@micahthomas talks about the auto move extension e.g. Windows should be created on the configured workspace and not moving windows to an other workspace using the keyboard. 
The feature is available as feature branch and i'm waiting for feedback

**Comment by micahthomas** [comment]
@negesti Thanks for the feature branch, i'll test it out today.

**Comment by micahthomas** [comment]
@negesti Awesome! works great. I'll keep testing it & If I see bugs, i'll add new issue.

**Comment by negesti** [comment]
merged into develop

**Comment by sojusnik** [comment]
So how do you actually use it then? I have the latest version from extensions.gnome.org, using Ubuntu 16.04, but don't see a workspace setting, like shown [here](http://i.imgur.com/PDS0VdD.png).

**Comment by negesti** [comment]
You habe to enable workspace support in main settings

Am 24.11.2016 20:00 schrieb "sojusnik" <notifications@github.com>:
