### ISSUE TITLE
Clear key-binding

### ISSUE THREAD

**Issue by paller** [negesti/gnome-shell-extensions-negesti#79]
It would be useful to have an option for clearing key-bindings.

As there is no option for clearing the key-binding for a shortcut, I'm currently assigning the same strange key combination to all the shortcuts that I don't want to use.

**Comment by negesti** [comment]
you can not clear the keybinding (not sure why the input element doesn't support that) but you can disable the move operations you don't want

**Comment by paller** [comment]
If it's the text-box that doesn't allow it, would it be possible to add a 'clear' button next to each keybinding?

**Comment by negesti** [comment]
don't see the point of adding a clear option as there already exists a enabled checkbox.
Just uncheck if you don't need the keybinding

**Comment by paller** [comment]
For some reason I totally overlooked that, may even have confused it with the settings for another extension.

I'm sorry for the inconvenience.
