### ISSUE TITLE
super+L shortcut conflicts with gnome-shell's Lock Screen shortcut (super+L)

### ISSUE THREAD

**Issue by fastrizwaan** [negesti/gnome-shell-extensions-negesti#82]
Gnome-shell has Super+L for Lock screen, which I use a lot. Put windows overrides that and I can't lock the screen with default lock screen shortcut, unless I replace super+L to something else in putwindows's extensions settings. Please consider changing super+L to something else. Thanks.
![screenshot from 2015-08-22 08-47-40](https://cloud.githubusercontent.com/assets/1161682/9422279/06d756aa-48ab-11e5-853d-81c76070aa84.png)

**Comment by negesti** [comment]
any suggestions for a default keybinding?

**Comment by fastrizwaan** [comment]
as the focus is "shifted", I'd suggest using 

"Shift+Super+I"  - move the window focus up
"Shift+Super+L" - move the window focus right
"Shift+Super+K" - move the window focus down
"Shift+Super+L" - move the window focus left

Thanks.
