### ISSUE TITLE
Windows not aligned properly top-left, bottom-left, top-right and bottom-right

### ISSUE THREAD

**Issue by fastrizwaan** [negesti/gnome-shell-extensions-negesti#84]
I want to have 4 windows with equal sizes 50-50 size, so that I could work with 4 windows.
The Top Left and Top Right and Bottom Left and Bottom right ( window beside window is properly arranged)

But 

Top Left and Bottom Left windows and Top Right and Bottom Right windows are overlapping each other.

Please observe the title bar of Bottom Left and Bottom Right windows here and in the next image

![screenshot from 2015-09-05 12-53-33](https://cloud.githubusercontent.com/assets/1161682/9698292/2a6b1ee4-53cd-11e5-8190-e442fc9e324a.png)
![screenshot from 2015-09-05 12-55-51](https://cloud.githubusercontent.com/assets/1161682/9698309/cfc33052-53cd-11e5-99c5-feae112e4837.png)

The titlebar size is ignored it seems. Please take full window size to calculate 50% of the window size. Thanks.

**Comment by fastrizwaan** [comment]
looks like the top-bar size is not taken into consideration, for gedit, whereas with firefox The whole titlebar, tabs and location bar are overlapped by the top window.

**Comment by fastrizwaan** [comment]
This is How to try this: open 4 windows of say firefox/gedit

press super+5 followed by super+7, super+1, super+9, super+3 for each window

**Comment by negesti** [comment]
Definitely a bug, but im not aure if this can be fixed. Sie is always calculated using the whole window dimension. 
Anyway, whats the usecase for such a window alignment?
