### ISSUE TITLE
does not work anymore after update

### ISSUE THREAD

**Issue by lduvaux** [negesti/gnome-shell-extensions-negesti#86]
I had the extension installed for a long while. 
I just updated it using the specific icon on the gnome-extension website.
Since then, although the extension is still installed (I can change the settings in tweak tool, set it off/on), the shortcuts do not work anymore (i.e. I cannot move the windows around as before).

I tried to uninstall/reinstall but this didn't fix the problem.

Version information:

    Shell version: 3.10.4
    Extension version: 18

Ubuntu

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.3 LTS
    Release:	14.04
    Codename:	trusty

**Comment by negesti** [comment]
hm looks like a syntax error. any error messages in looking Glas when you active the extension?

e.g.  Alt+F2 "lg",  Extension, PutWindows, "Show errors"

**Comment by lduvaux** [comment]
no sorry
`putWindows@clemens.lab21.org has not emitted errors`

**Comment by negesti** [comment]
just installed ubuntu 14 and tested the extension there. Can you please the github version (branch develop).
