### ISSUE TITLE
Gnome Shell 3.18 support

### ISSUE THREAD

**Issue by egyptianbman** [negesti/gnome-shell-extensions-negesti#87]
Hello,

I'm on Gnome Shell 3.18.1 and am having issues installing this extension.  I could not install it via extensions.gnome.org but was able to get it installed manually.  The problem now is I can't enable it, the site tells me it's outdated.  Any insight you can provide would be greatly appreciated; thanks!

**Comment by negesti** [comment]
i had no time to update to Fedora 23 and gnome-shell 3.18 yet and haven't check, if the extension is working properly.

If you are lucky you can just add 3.18 to the shell-version array in ~/.local/share/gnome-shell/extensions/putWindow@clemens.lab21.org/metadata.json

e.g. it should look like this:

    {     
      "shell-version": ["3.4", "3.5.2", "3.6", "3.8", "3.10", "3.12", "3.14", "3.16", "3.18"],
      "uuid": "putWindow@clemens.lab21.org",
      "name": "Put Windows",
      "description": "Fully customizable replacement for the old compiz put plugin. \n * Move windows to left/right side, bottom/top, center or corner \n * Move window to other screen \n * Select focused window using the keyboard \n * Application based window placement",
      "url": "https://github.com/negesti/gnome-shell-extensions-negesti",
      "settings-schema": "org.gnome.shell.extensions.org-lab21-putwindow"
    }

**Comment by egyptianbman** [comment]
It looks to be working fine.  There were some oddities like I had to re-set the key bindings but other than that, everything seems to be working.

**Comment by motdef** [comment]
Seems to be working with GNOME 3.18. I haven't tried this extension before, but it looks to me like the "Keep width when moving north/south" setting is duplicated: 
![1447802460](https://cloud.githubusercontent.com/assets/12588098/11228033/e6a9af7e-8d81-11e5-99fe-717201b7b4d4.png)

**Comment by egyptianbman** [comment]
Something that may be of interest:

```
(gnome-shell:31074): Gjs-WARNING **: JS ERROR: Could not load extension put-window: Error: uuid "putWindow@clemens.lab21.org" from metadata.json does not match directory name "put-window"
```
