### ISSUE TITLE
Multi-Monitor Positioning

### ISSUE THREAD

**Issue by darkfrog26** [negesti/gnome-shell-extensions-negesti#89]
I have a four monitor setup (2x2) and it always tries to move it to the first monitor instead of staying on the screen it was positioned on in the first place.

**Comment by negesti** [comment]
sounds like the extension fails to calculate the correct screen in your setup. 
Can you enable "Always use multiple widths/heights" maybe that helps.

I can not reproduce your setup with my notebook. But the problem is that extension.js#138 _getCurrentScreenIndex uses "_isVerticalScreenSetup" and then only checks x position **or** y position

**Comment by darkfrog26** [comment]
I tried "Always use multiple widths/heights" and it doesn't seem to make any difference.

What's interesting is that it seems to work okay for the top-left display and the bottom-right display except for sometimes it glitches on the bottom-right display and jumps to the top-right display.

**Comment by darkfrog26** [comment]
BTW, I am a programmer and know JavaScript fairly well. However, I have not written an extension before, so I'm not really sure the process of debugging this.  How do you access logging info and can I simply modify the extension.js file in the extensions folder and see the change immediately?

**Comment by negesti** [comment]
Maybe this is enough for resizing the windows.
There may still be some problems when moving a window to an other screen, as the extensions currently expects max 2 screens and uses _isVerticalScreenSetup to check if they the window should be moved left/right or up/down.
Basically you can use `global.log("string");` similar to `console.log()` you have inside a browser. Changes made to extension.js require a shell restart. I normally debug the extension using global.log and then restart the shell inside a terminal using `gnome-shell --replace &`. This way the logs are redirected to the console and not to journalctl or a log file

**Comment by darkfrog26** [comment]
Thanks for the tips. I'll do some testing against this when I get a chance.  If I get anywhere I'll submit a PR.

**Comment by negesti** [comment]
fixed a bug yesterday that caused problems after lock/unlock. Should work now for more then two screens

**Comment by negesti** [comment]
@darkfrog26 can we close this? does it work for you?

**Comment by darkfrog26** [comment]
Sorry, I haven't tested it.  I switched to using i3 instead.
