### ISSUE TITLE
Add option to disable window flash on focus

### ISSUE THREAD

**Issue by dradtke** [negesti/gnome-shell-extensions-negesti#90]
I like the extension a lot for being able to quickly change window focus, but after installing it on a new installation of GNOME 3.16, I noticed it started doing a weird white flash over each window when it moved focus to it. It's kind of a cool effect, but I wasn't really a fan, and there wasn't an option in the settings to disable it. I managed to disable it by modifying `moveFocus.js`:

```js
_activateWindow: function(window) {
    // this._flashWindow(window); <-- comment this line out
    window.activate(global.get_current_time());
},
```

and now I can switch focus without the flash effect. Ideally, this would be a toggle-able setting so that users don't have to modify the extension's javascript to disable the effect.

**Comment by 73** [comment]
You're right. I added the flash because it was sometimes hard to tell to which window the focus was changed to. And I agree it should have a setting. But I'm not that into the settings thing. Maybe @negesti  could add a switch?

**Comment by negesti** [comment]
I will add a switch in the settings menu.

**Comment by negesti** [comment]
added a switch to the settings. It should work but i'm not really able to test it.
(If have another "personal use" extension that disabled animation in the whole shell. Re-enabling its seams to be buggy)

**Comment by negesti** [comment]
any feedback?

**Comment by 73** [comment]
Oh. Nobody answered. Works like a charm! Thank you very much @negesti.
