### ISSUE TITLE
Support for 3.18?

### ISSUE THREAD

**Issue by markolenik** [negesti/gnome-shell-extensions-negesti#91]
Has this been tested on Gnome Shell 3.18? I'm having trouble installing it but that maybe because something is wrong with my setup.

**Comment by negesti** [comment]
Works on my fedora 23 system but i have installed it manually from github

**Comment by Geraint** [comment]
Not working for me on Fedora 23.  When I look at it on [extensions.gnome.org](https://extensions.gnome.org/extension/39/put-windows/), it says "outdated".

**Comment by negesti** [comment]
the github version works with 3.18. I just uploaded a the version extensions.gnome.org. I may take some days to be available there
