### ISSUE TITLE
Windows don't align to the top and bottom of the screen, there are empty pixels between the window and the edge

### ISSUE THREAD

**Issue by joelostblom** [negesti/gnome-shell-extensions-negesti#92]
Thank you so muh for making this extension, I wouldn't be using Gnome without it!

The only issue I have encountered is that when I move windows to corners or top/bottom, they do not go all the way to the screen edge.

Top:
![screenshot from 2016-02-24 09-32-41](https://cloud.githubusercontent.com/assets/4560057/13288362/99adcc32-dad9-11e5-802b-375157831084.png)

Bottom:
![screenshot from 2016-02-24 09-33-30](https://cloud.githubusercontent.com/assets/4560057/13288390/b33814b4-dad9-11e5-839e-a86a6e738cce.png)

This is also true for windows that span the entire width of the screen (place bottom or top), but not for maximized windows, which behave as expected and fill up the entire screen.

Interestingly, when I use the autoplace option for newly created windows (x=0 y=0), the window lines up in the corner perfectly and there are not pixels between it and the status bar.

I am using the version of [the plugin available from the gnome extensions home page](https://extensions.gnome.org/extension/39/put-windows/) and I am on Arch Linux (antergos) with Gnome 3.18.2.

**Comment by negesti** [comment]
Thanks for you feedback! glad to here that. 
The problem is very strange. I have never seen a gap at the bottom of the screen. The extension support "auto hide top bar" which resulted in a gap at the top of the screen "back in the early days".

* Do you have any other extensions installed for top/bottom bar?
* does this happen with all applications? (some apps have very strange window padding/margin rendering)

**Comment by joelostblom** [comment]
Thanks for your reply negesti,
The problem was present with all applications originally. However, it went away when I disabled all other extensions, and after enabling them one by one and restarting, the issue has yet to reappear. So everything is working fine now, although I am not sure what what going on previously =)
