### ISSUE TITLE
Support Gnome 3.20

### ISSUE THREAD

**Issue by 314eter** [negesti/gnome-shell-extensions-negesti#95]

**Comment by negesti** [comment]
Currently i don't have the time to setup a vm and work on the extension.

Have you tried to add 3.20 to the array of supported versions in metadata.json? Maybe that is enough

**Comment by joelostblom** [comment]
Thanks, I can confirm that adding 3.20 in `metadata.json` works! I was scared for a while there... this is such a great extension and it is what makes Gnome usable for me  =) Thanks for making it and keeping it up to date!

**Comment by eddy-geek** [comment]
Seems like the gnome 3.20 version hasn't been released to extensions.gnome.org. Can you do it (or reopen this issue until you do - I almost opened a new issue)

**Comment by negesti** [comment]
v3.20 is currently reviewed at extensions.gnome.org.

**Comment by negesti** [comment]
just got the notification that the extension was reviewed. v3.20 is not available from extensions.gnome.org

**Comment by eddy-geek** [comment]
That was quick!
Verified working -- though the new placement computation code to fix #96 seems to count gnome-shell statusbar twice...
Thanks.
