### ISSUE TITLE
Putting applications windows to the specific workspaces doesnt work

### ISSUE THREAD

**Issue by Bastian82** [negesti/gnome-shell-extensions-negesti#97]
Hi,
Im using Ubuntu 14.04 with gnome 3.10. The goal i wanted to archieve was to put specific apps to the specific workspaces. Mostly im working with 2 screens  (laptop + 22 monitor). This extension is what i was looking for but it doesnt work for me, or i cannot use it properly maybe..
What i did:
Main settings-> Enable move to workspace -> ON
Applications-> 'Whatever app taken form list' -> Move window to workspace when created -> ON
                                                                        -> Window target workspace -> 2
                                                                        -> Auto-Move window when created ->ON
                                                                        -> Screen 2 (monitor 22')

Moving between screens seems to work properly,  width and height settings per application as well, but whenever i run any application defined it doesnt open in selected workspace. It always opens in workspace 1 (on screen 1 or screen2 depend what i choosed)

Thanks,

**Comment by negesti** [comment]
Just tested it and it looks ok with the gnome v3.18. 
Maybe it's just not compatible with 3.10. Can you place start gnome-shell from console and post the log/error messages here?

 ` gnome-shell --replace & `

**Comment by johnyf** [comment]
Does not work for `gitg` and other programs in Gnome v3.14 nor v3.20.1. In particular, launching them from the command line, in a terminal in Screen 2 leaves them in Screen 2, instead of moving them to Screen 1.

**Comment by negesti** [comment]
nearly the complete code is copied from the [AutoMoveWindows Extension](https://extensions.gnome.org/extension/16/auto-move-windows/). Maybe updating the code to a newer version of the extension fixed the issues.

**Comment by negesti** [comment]
sry it took that long, but it should work now
